export function mountParkour(root,ctx){
 root.innerHTML=`<div class="arc-intro"><div><span class="eyebrow">05 / MOONLIT JOURNEY</span><h2>跟着玉兔，奔向月亮。</h2><p>空格 / ↑ / 轻点画面起跳，空中可再跳一次。穿过三段月夜，跑满 3000 米。</p></div><div class="arc-actions"><button class="btn arc-run">启程奔月</button><button class="btn secondary arc-pause" disabled>暂停</button></div></div><div class="arc-stats"><div><small>奔月路程</small><strong data-distance>0 <em>/ 3000 m</em></strong></div><div><small>玉兔体力</small><strong data-life>♥ ♥ ♥</strong></div><div><small>收集月币</small><strong data-coins>0</strong></div><div><small>当前旅程</small><strong data-stage>桂花小径</strong></div></div><div class="arc-canvas-wrap"><canvas class="arc-canvas" aria-label="玉兔跑酷游戏，空格键跳跃" tabindex="0"></canvas><div class="arc-run-message">桂花小径 → 流云天阶 → 广寒月宫<br><small>点击「启程奔月」开始冒险</small></div></div><div class="arc-legend"><span>♡ 三次受伤机会</span><span>◈ 护盾：抵挡一次碰撞</span><span>◎ 磁铁：吸收附近月币</span><span>↗ 冲刺：短暂无敌加速</span></div><p class="arc-run-record">本机最远纪录：<strong data-run-record>${ctx.get('parkour-best',0)}</strong> 米</p><p class="arc-run-status" role="status">月亮在前方等你。每 1000 米进入下一关，速度随旅程提升。</p>`;
 const $=s=>root.querySelector(s),canvas=$('canvas'),g=canvas.getContext('2d');let raf,active=false,paused=false,last=0,t=0,distance=0,coins=0,life=3,objects=[],spawn=0,invincible=0,shield=0,magnet=0,dash=0,ground=280,y=280,vy=0,jumps=0,stage=0;
 const stages=['桂花小径','流云天阶','广寒月宫'];let W=1000;canvas.height=360;function resize(){const next=canvas.parentElement.clientWidth<650?640:1000;if(canvas.width!==next){W=next;canvas.width=W;}}resize();const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(canvas.parentElement);
 function ui(){ $('[data-distance]').innerHTML=`${Math.floor(distance)} <em>/ 3000 m</em>`;$('[data-life]').textContent='♥ '.repeat(life)+'♡ '.repeat(3-life);$('[data-coins]').textContent=coins;$('[data-stage]').textContent=stages[stage];}
 function end(won){active=false;$('.arc-pause').disabled=true;$('.arc-run').textContent='再跑一次';$('.arc-run-message').style.display='block';$('.arc-run-message').innerHTML=won?`已抵达广寒月宫！<br><small>收集 ${coins} 枚月币，奔月印章已点亮</small>`:`稍作歇息，再出发吧。<br><small>跑过 ${Math.floor(distance)} 米 · 收集 ${coins} 枚月币</small>`;if(won)ctx.award('parkour');ctx.set('parkour-best',Math.max(Math.floor(distance),ctx.get('parkour-best',0)));$('[data-run-record]').textContent=ctx.get('parkour-best',0);}
 function jump(){if(!active||paused)return;if(jumps<2){vy=-470;jumps++;}}
 function start(){active=true;paused=false;last=0;t=0;distance=coins=stage=0;life=3;objects=[];spawn=1;invincible=shield=magnet=dash=0;y=ground;vy=jumps=0;$('.arc-run-message').style.display='none';$('.arc-pause').disabled=false;$('.arc-pause').textContent='暂停';$('.arc-run').textContent='重新启程';$('.arc-run-status').textContent='轻点跳跃，连续轻点可双跳。看到月币就去收集吧！';ui();canvas.focus();}
 function circle(x,y,r,c){g.fillStyle=c;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill();}
 function render(dt){g.clearRect(0,0,W,360);g.fillStyle=['#191c30','#242036','#271b30'][stage];g.fillRect(0,0,W,360);circle(W*.815,87,51,'#e0bc71');circle(W*.815-20,76,6,'#d7ae62');circle(W*.815+23,108,10,'#d7ae62');g.strokeStyle='#c7a86d33';g.lineWidth=1;for(let i=0;i<8;i++){let x=((i*170-t*15)%1300+1300)%1300-150;g.beginPath();g.ellipse(x,175+(i%3)*15,110,25,0,Math.PI,0);g.stroke();}g.fillStyle='#374b42';g.beginPath();g.moveTo(0,ground);for(let x=0;x<=W;x+=10)g.lineTo(x,ground-12-Math.sin(x/160+t*.1)*12);g.lineTo(W,360);g.lineTo(0,360);g.fill();g.strokeStyle='#e8c38b';g.beginPath();g.moveTo(0,ground+5);g.lineTo(W,ground+5);g.stroke();g.fillStyle='#bba88340';for(let i=0;i<30;i++){let x=((i*47-t*100)%1100+1100)%1100;g.fillRect(x,310+(i%3)*12,12,1);}
 for(const o of objects){if(o.type==='rock'){g.fillStyle='#766479';g.strokeStyle='#bb9383';g.beginPath();g.moveTo(o.x-20,ground);g.lineTo(o.x-23,ground-25);g.lineTo(o.x-5,ground-44);g.lineTo(o.x+19,ground-32);g.lineTo(o.x+23,ground);g.closePath();g.fill();g.stroke();}else{circle(o.x,o.y,13,o.type==='coin'?'#d1a84f':'#e8c38b');g.fillStyle='#fff8e8';g.font='bold 15px sans-serif';g.textAlign='center';g.fillText(({coin:'月',shield:'盾',magnet:'磁',dash:'冲'})[o.type],o.x,o.y+5);}}
 g.save();g.translate(135,y);if(invincible>0&&Math.floor(t*12)%2===0)g.globalAlpha=.45;if(shield>0||dash>0){g.strokeStyle=dash>0?'#ae4935':'#c5a053';g.lineWidth=3;g.beginPath();g.arc(0,-25,39,0,Math.PI*2);g.stroke();}g.fillStyle='#faf5e8';g.strokeStyle='#e8c38b';g.lineWidth=2;g.beginPath();g.ellipse(-4,-23,22,24,0,0,Math.PI*2);g.fill();g.stroke();g.beginPath();g.ellipse(10,-44,17,17,0,0,Math.PI*2);g.fill();g.stroke();for(let z=0;z<2;z++){g.beginPath();g.ellipse(5+z*14,-68,5,19,z*.2,0,Math.PI*2);g.fill();g.stroke();}circle(17,-48,2,'#e8c38b');circle(-26,-21,7,'#faf5e8');g.fillStyle='#ae4935';g.fillRect(-1,-34,22,5);g.beginPath();g.moveTo(2,-33);g.lineTo(-17,-27);g.lineTo(-8,-23);g.fill();g.strokeStyle='#e8c38b';g.beginPath();g.moveTo(-12,-5);g.lineTo(-18+(active?Math.sin(t*18)*6:0),1);g.moveTo(9,-4);g.lineTo(18-(active?Math.sin(t*18)*6:0),1);g.stroke();g.restore();if(shield||magnet>0||dash>0){g.fillStyle='#e8c38b';g.font='14px sans-serif';g.textAlign='left';g.fillText(`${shield?'护盾已装备  ':''}${magnet>0?'磁铁 '+Math.ceil(magnet)+'s  ':''}${dash>0?'冲刺 '+Math.ceil(dash)+'s':''}`,25,30);}}
 function frame(ts){let dt=Math.min((ts-last)/1000||0,.035);last=ts;if(active&&!paused){t+=dt;const speed=(285+stage*45)*(dash>0?1.55:1);distance=Math.min(3000,distance+dt*speed/7);stage=Math.min(2,Math.floor(distance/1000));invincible=Math.max(0,invincible-dt);magnet=Math.max(0,magnet-dt);dash=Math.max(0,dash-dt);vy+=1150*dt;y+=vy*dt;if(y>=ground){y=ground;vy=0;jumps=0;}spawn-=dt;if(spawn<=0){const r=Math.random();objects.push({x:W+50,type:r<.49?'rock':r<.84?'coin':r<.90?'shield':r<.96?'magnet':'dash',y:ground-55-Math.random()*65});spawn=.95+Math.random()*.65;}for(const o of objects){o.x-=speed*dt;if(o.hit)continue;if(o.type==='rock'){if(Math.abs(o.x-135)<36&&y>ground-44){o.hit=true;if(dash>0||invincible>0){}else if(shield){shield=0;invincible=1;}else{life--;invincible=1.5;$('.arc-run-status').textContent='撞到月石了！提前起跳，空中还能再跳一次。';if(life<=0)end(false);}}}else if(Math.hypot(o.x-135,o.y-(y-28))<(magnet>0&&o.type==='coin'?160:40)){o.hit=true;if(o.type==='coin')coins++;if(o.type==='shield')shield=1;if(o.type==='magnet')magnet=8;if(o.type==='dash')dash=4;}}objects=objects.filter(o=>o.x>-50&&!(o.hit&&o.type!=='rock'));ui();if(distance>=3000&&active)end(true);}render(dt);raf=requestAnimationFrame(frame);}
 $('.arc-run').onclick=start;$('.arc-pause').onclick=()=>{paused=!paused;$('.arc-pause').textContent=paused?'继续':'暂停';$('.arc-run-message').style.display=paused?'block':'none';$('.arc-run-message').innerHTML='月下小憩<br><small>点击「继续」返回旅程</small>';};canvas.addEventListener('pointerdown',jump);const key=e=>{if(e.code==='Space'||e.code==='ArrowUp'){if(e.target instanceof HTMLElement&&['BUTTON','INPUT','SUMMARY'].includes(e.target.tagName))return;e.preventDefault();if(!e.repeat)jump();}};window.addEventListener('keydown',key);raf=requestAnimationFrame(frame);return()=>{resizeObserver.disconnect();cancelAnimationFrame(raf);window.removeEventListener('keydown',key);canvas.removeEventListener('pointerdown',jump);};
}
