import {mountMooncake,mountParkour} from './games/arcade.js';
import {mountQuiz,mountPersona,mountWall} from './games/social.js';

const root=document.querySelector('#main');
document.querySelector('.skip-link').addEventListener('click',e=>{e.preventDefault();root.focus();root.scrollIntoView({behavior:'instant'});});
const games=[
 {id:'mooncake',name:'月饼工坊',sub:'MOONCAKE WORKSHOP',tag:'手速挑战',description:'五味月饼，分出一份团圆。',time:'约 1 分钟',stamp:'团',rule:'一局获得 100 分',mount:mountMooncake},
 {id:'quiz',name:'月下小考',sub:'MOONLIGHT QUIZ',tag:'中秋知识',description:'猜一猜，月亮藏了多少故事？',time:'8 道趣味问答',stamp:'知',rule:'完成一轮八题问答',mount:mountQuiz},
 {id:'persona',name:'月宫来信',sub:'A LETTER FROM THE MOON',tag:'人格测试',description:'看看月宫里的你，是谁。',time:'12 次心动选择',stamp:'缘',rule:'完成十二题角色测试',mount:mountPersona},
 {id:'wall',name:'心愿灯会',sub:'WISH UPON THE MOON',tag:'寄语中秋',description:'把没说完的话，交给月光。',time:'留一盏心愿灯',stamp:'愿',rule:'存下一条中秋心愿',mount:mountWall},
 {id:'parkour',name:'玉兔奔月',sub:'THE RABBIT JOURNEY',tag:'轻松跑酷',description:'越过山海，一起奔向月亮。',time:'3 段奔月旅程',stamp:'跃',rule:'跑完三关 3000 米',mount:mountParkour}
];
let cleanup=()=>{},toastTimer,audioContext,sound=false;
function get(key,fallback){try{const v=JSON.parse(localStorage.getItem('moon-garden:'+key));return v===null?fallback:v;}catch{return fallback;}}
function set(key,value){try{localStorage.setItem('moon-garden:'+key,JSON.stringify(value));}catch{toast('当前浏览器无法保存数据，离开页面后可能丢失。');}}
function stamps(){const saved=get('stamps',[]);return Array.isArray(saved)?saved.filter(id=>games.some(g=>g.id===id)):[];}
function updateCount(){document.querySelector('#stamp-count').textContent=stamps().length+'/5';}
function toast(text){const el=document.querySelector('#toast');clearTimeout(toastTimer);el.textContent=text;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function playTone(){if(!sound||!audioContext)return;const now=audioContext.currentTime;[523.25,659.25,783.99].forEach((freq,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0,now+i*.07);gain.gain.linearRampToValueAtTime(.055,now+i*.07+.02);gain.gain.exponentialRampToValueAtTime(.001,now+i*.07+.45);osc.connect(gain);gain.connect(audioContext.destination);osc.start(now+i*.07);osc.stop(now+i*.07+.5);});}
function award(id){const all=stamps();if(all.includes(id)||!games.some(g=>g.id===id))return;all.push(id);set('stamps',all);updateCount();playTone();toast(`收集「${games.find(g=>g.id===id).stamp}」字印章！已集齐 ${all.length} / 5 枚`);}
document.querySelector('#sound').onclick=async()=>{try{if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();sound=!sound;const btn=document.querySelector('#sound');btn.setAttribute('aria-pressed',String(sound));btn.setAttribute('aria-label',sound?'关闭游园音效':'开启游园音效');btn.querySelector('.sound-label').textContent=sound?'音效开':'音效关';if(sound)playTone();}catch{toast('当前浏览器暂不支持音效。');}};
document.addEventListener('click',e=>{if(e.target.closest('a,.btn')&&!e.target.closest('#sound'))playTone();});
function illustration(id){const start='<svg class="card-art" viewBox="0 0 220 160" fill="none" aria-hidden="true">';const end='</svg>';
 if(id==='mooncake')return start+`<ellipse cx="114" cy="126" rx="87" ry="19" fill="#c5cdb7"/><ellipse cx="114" cy="122" rx="88" ry="19" fill="#f7f1df" stroke="#8c9b7c"/><ellipse cx="114" cy="122" rx="69" ry="12" stroke="#c4c8ac"/><g transform="translate(74 87)"><path d="M0-35q14-13 24 0q21-3 24 17q18 14 3 31q4 21-18 24q-16 16-32 2q-21 3-26-18q-18-16-3-33q-4-20 28-23Z" fill="#d7a75b" stroke="#a17a42" stroke-width="2"/><circle cy="4" r="27" stroke="#f3dba2" stroke-width="2"/><circle cy="4" r="22" stroke="#a17a42"/><text y="14" text-anchor="middle" font-family="serif" font-size="24" fill="#895e31">团</text></g><g transform="translate(146 59) scale(.84)"><path d="M0-35q14-13 24 0q21-3 24 17q18 14 3 31q4 21-18 24q-16 16-32 2q-21 3-26-18q-18-16-3-33q-4-20 28-23Z" fill="#b9c595" stroke="#7e9568" stroke-width="2"/><circle cy="4" r="27" stroke="#f2eed4" stroke-width="2"/><circle cy="4" r="21" stroke="#7e9568"/><text y="14" text-anchor="middle" font-family="serif" font-size="24" fill="#637c54">圆</text></g><path d="M174 112q35-23 35 0q-24 17-35 0Z" fill="#547960"/><path d="M179 113l22-4" stroke="#ecedd8"/>`+end;
 if(id==='quiz')return start+`<path d="M59 33q15-5 91 4v96q-54-14-91-2Z" fill="#f9f3df" stroke="#9a9875" stroke-width="1.5"/><path d="M66 27q45-6 92 3v96q-45-13-92-2Z" fill="#f7f0d9" stroke="#9a9875" stroke-width="1.5"/><path d="M76 30v89M81 37h65M82 110h65" stroke="#b1ad87"/><path d="M143 41v46m-17-46v36m-17-35v48M94 43v31" stroke="#8e9270" stroke-width="2" stroke-dasharray="7 3"/><path d="M53 34l-15 107" stroke="#284e40" stroke-width="8"/><path d="M36 141l-2 13l9-12" fill="#284e40"/><path d="M169 113l16-82" stroke="#ae4935" stroke-width="7"/><path d="M166 112l1 25l9-22" fill="#284e40"/><circle cx="111" cy="103" r="8" stroke="#ae4935"/><path d="M183 13v13m-6-6h12" stroke="#b29b65"/>`+end;
 if(id==='persona')return start+`<circle cx="132" cy="69" r="49" fill="#e4cb8a"/><path d="M74 44l68-13l20 99l-69 13Z" fill="#f9f2de" stroke="#a4aa8b"/><path d="M80 50l56-11l16 84l-54 11Z" stroke="#c5c7a8"/><path d="M98 66l33-6m-30 20l33-6m-30 20l21-4" stroke="#aeb296"/><circle cx="128" cy="111" r="12" fill="#ae4935"/><text x="128" y="116" text-anchor="middle" font-size="14" fill="#f5e5c3" font-family="serif">缘</text><path d="M160 62q17-28 37-18q-8 30-37 18Z" fill="#68896e"/><path d="M163 64l31-17" stroke="#e0e6ce"/><path d="M53 106v20m-10-10h20" stroke="#b39c65"/>`+end;
 if(id==='wall')return start+`<path d="M109 10v28" stroke="#8c906c"/><path d="M83 40h53v7H83Z" fill="#284e40"/><path d="M75 47q-13 42 3 65h63q17-32 1-65Z" fill="#bf684c" stroke="#a7513b"/><path d="M90 48q-10 34 0 62m20-62v62m21-62q10 34 0 62" stroke="#e7ab73"/><path d="M78 112h64v7H78Z" fill="#284e40"/><path d="M109 119v29m-5-13v18m10-18v18" stroke="#ae4935" stroke-width="2"/><circle cx="110" cy="80" r="20" fill="#f3ddb0"/><text x="110" y="88" text-anchor="middle" font-size="24" font-family="serif" fill="#ae4935">愿</text><path d="M169 52v13m-6-6h12M47 105v13m-6-6h12" stroke="#b19a5e"/>`+end;
 return start+`<circle cx="157" cy="50" r="31" fill="#dfbe76"/><path d="M25 137h171m-143 8h84" stroke="#9da98a"/><g stroke="#48634c" stroke-width="1.6"><ellipse cx="109" cy="107" rx="38" ry="24" fill="#fff9e9"/><circle cx="143" cy="86" r="22" fill="#fff9e9"/><ellipse cx="136" cy="57" rx="7" ry="25" transform="rotate(-20 136 57)" fill="#fff9e9"/><ellipse cx="154" cy="58" rx="7" ry="24" transform="rotate(10 154 58)" fill="#fff9e9"/><circle cx="72" cy="104" r="10" fill="#fff9e9"/><path d="M91 123l-13 10m44-10l15 8" stroke-width="5" stroke-linecap="round"/></g><circle cx="151" cy="83" r="2.4" fill="#284e40"/><path d="M127 101l29 1l-2 8l-27-1l-27 15l3-12Z" fill="#ae4935"/><path d="M35 85h29m-18 13h12" stroke="#889b7b"/>`+end;
}
function home(){const collected=stamps();root.innerHTML=`<section class="hero container"><div class="hero-copy"><div class="eyebrow hero-kicker">2026 中秋特别企划 · 线上游园会</div><h1>月圆之夜，<br>来园里<em>逛逛。</em></h1><p>把日子放慢一点，把团圆留长一点。<br>跟着玉兔赴一场月下之约，<br>分月饼、猜灯谜，收集属于你的中秋小欢喜。</p><div class="hero-actions"><a class="btn" href="#/guide">提灯入园 <span>↗</span></a><a class="text-link" href="#/wall">先许个心愿 <span>→</span></a></div><div class="hero-foot"><span></span> 不必赶路 · 随时入园 · 好心情不限量</div></div><div class="hero-art"><img src="assets/garden.svg" alt="纸绘风格的中秋花园：金色满月、桂花树与灯笼、抱月饼的玉兔和远处月宫" width="760" height="620"><div class="date-stamp"><small>丙午年 · 中秋</small><strong>九月廿五</strong><span>花好 · 月圆</span></div></div></section>
<div class="ribbon" aria-label="中秋祝愿"><span>月满人团圆</span><i>✦</i><span>桂香入好梦</span><i>✦</i><span>灯火照归途</span><i>✦</i><span>人间共此时</span><i>✦</i><span>好事正发生</span></div>
<section class="guide container" id="guide"><div class="section-top"><div><span class="eyebrow">THE GARDEN GUIDE / 游园指南</span><h2>五个小摊，一晚好时光。</h2></div><p>不设路线，不必争先。<br>走到哪儿，玩到哪儿，每一站都有小欢喜。</p></div><div class="cards">${games.map((g,i)=>`<a class="game-card" href="#/${g.id}"><div class="card-top"><b>0${i+1}</b><span> / ${g.tag}</span></div>${collected.includes(g.id)?'<span class="card-stamp">已集章</span>':''}${illustration(g.id)}<div class="card-copy"><h3>${g.name}</h3><p>${g.description}</p></div><div class="card-bottom"><span>${g.time}</span><span class="card-arrow">↗</span></div></a>`).join('')}</div><a class="progress-banner" href="#/stamps"><div><p>把月光，集成一份纪念。</p><small>完成玩法收集五枚印章，留住这晚的好时光。查看我的集章 ↗</small></div><div class="mini-stamps" aria-label="已收集 ${collected.length} 枚印章">${games.map(g=>`<span class="${collected.includes(g.id)?'done':''}">${g.stamp}</span>`).join('')}</div></a></section>
<div class="container"><section class="wish-section"><div><span class="eyebrow">LET THE MOON CARRY YOUR WISHES</span><h2>有些想念，<br>月亮替你记得。</h2><p>给远方的家人，给并肩的朋友，<br>也给正在努力的自己。<br>点一盏心愿灯，让温柔在今晚停留。</p><a href="#/wall" class="text-link">写下我的中秋心愿 <span>↗</span></a></div><div class="wish-art" aria-label="心愿示例"><span class="wish-moon"></span><div class="wish-note">愿所念皆如愿，<br>月圆人团圆。<small>一盏心愿 · 示例</small></div><div class="wish-note">日子慢慢，<br>幸福满满。<small>一盏心愿 · 示例</small></div><span class="wish-star">✦</span></div></section></div>`;}
function showStamps(){const collected=stamps();root.innerHTML=`<section class="info-page"><a href="#/guide" class="back-link">← 回到游园地图</a><div class="eyebrow" style="margin-top:35px">MY GARDEN PASSPORT / 我的游园手册</div><h1>一枚印章，<br>一段月下好时光。</h1><p class="info-lede">你的中秋纪念册已收集 ${collected.length} / 5 枚印章。每个小摊藏着一枚，慢慢逛，慢慢收集。</p><div class="stamp-grid">${games.map(g=>`<a href="#/${g.id}" class="stamp-item ${collected.includes(g.id)?'done':''}"><div class="stamp-circle">${g.stamp}</div><h2>${g.name}</h2><p>${collected.includes(g.id)?'已收集 · 再去逛逛 ↗':g.rule+' ↗'}</p></a>`).join('')}</div><div class="collection-status"><h2>${collected.length===5?'月光收集完成，祝你事事圆满。':'还有小欢喜，等着与你碰面。'}</h2><p>${collected.length===5?'五枚印章，一晚美好。你的中秋纪念已留在这本手册里。':'完成各摊位的挑战，就能点亮相应印章。'} 此纪念册保存在当前浏览器。</p></div></section>`;}
function story(){root.innerHTML=`<section class="info-page"><a href="#/" class="back-link">← 回到园门</a><div class="eyebrow" style="margin-top:35px">A FEW STORIES ABOUT THE MOON</div><h1>月亮很远，<br>团圆很近。</h1><p class="info-lede">八月十五，秋已过半。人们抬头望月，也把牵挂交给月光。我们把那些熟悉的中秋小事，装进了这座可以随时走进的花园。</p><div class="story-grid"><article class="story-card"><span>壹</span><h2>一轮月</h2><p>赏月，是中秋最温柔的仪式。无论此刻相隔多远，同一轮明月，让思念有了相遇的地方。</p></article><article class="story-card"><span>贰</span><h2>一口甜</h2><p>莲蓉、豆沙、五仁，或是一枚清爽冰皮。月饼可以有许多口味，分着吃的那一口，总有团圆的意思。</p></article><article class="story-card"><span>叁</span><h2>一盏灯</h2><p>提灯游园，把寻常夜晚照得明亮一些。在这里，猜一题、跑一程、许一个愿，让节日有自己的节奏。</p></article></div><a class="btn" href="#/guide">继续月下漫游 <span>↗</span></a></section>`;}
function route(){cleanup();cleanup=()=>{};const id=location.hash.slice(2).split('?')[0]||'';document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===id));const g=games.find(g=>g.id===id);if(g){document.title=g.name+' · 月满游园';root.innerHTML=`<section class="game-page"><header class="game-page-heading"><div><span class="eyebrow">${g.sub}</span><h1>${g.name}</h1></div><div class="game-heading-right"><a class="back-link" href="#/guide">← 回游园地图</a><span class="game-local">${g.id==='wall'?'心愿仅保存在本机':'成绩与印章保存在本机'}</span></div></header><div class="game-content"></div></section>`;cleanup=g.mount(root.querySelector('.game-content'),{get,set,toast,award})||(()=>{});}else if(id==='stamps'){showStamps();document.title='我的集章 · 月满游园';}else if(id==='story'){story();document.title='中秋小记 · 月满游园';}else if(id===''||id==='guide'){home();document.title='月满游园 · 2026 中秋游园手册';}else{root.innerHTML='<section class="info-page"><div class="eyebrow">这条小径还没开放</div><h1>月亮在园门等你。</h1><a class="btn" href="#/">回到园门 ↗</a></section>';document.title='回到园门 · 月满游园';}updateCount();window.scrollTo({top:0,behavior:'instant'});if(id==='guide')requestAnimationFrame(()=>document.querySelector('#guide')?.scrollIntoView({behavior:'instant'}));}
window.addEventListener('hashchange',route);route();
