import {useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {trackEvent} from '../../lib/analytics';
import {messageFits,type PostcardData} from '../../pages/postcard/render';
import {readLocal,writeLocal} from '../../pages/postcard/persistence';
import './send-letter.css';
type Sent={id:string;secret:string;createdAt:string;title:string};
const readSent=()=>{const items=readLocal<Sent[]>('sent-letters',[]);return Array.isArray(items)?items.filter(x=>x&&typeof x.id==='string'&&typeof x.secret==='string'):[];};
const link=(item:Sent,privateLink=false)=>`${location.origin}${location.pathname}#/${privateLink?'mailbox':'letter'}/${item.id}${privateLink?'/'+item.secret:''}`;
async function smallLogo(source:string){const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('标记图片读取失败，请重新上传。'));image.src=source;});const canvas=document.createElement('canvas');const scale=Math.min(1,256/Math.max(image.width,image.height));canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/webp',.82);if(result.length>160*1024)throw new Error('标记图片过大，请换一张较简单的图片。');return result;}
function secret(){return btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
export default function SendLetterPanel({data,logo,disabled}:{data:PostcardData;logo?:string;disabled:boolean}){
 const [sent,setSent]=useState(readSent);const [result,setResult]=useState<Sent|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [note,setNote]=useState('');
 const pending=useRef<{fingerprint:string;requestId:string;ownerSecret:string}|null>(readLocal('pending-letter',null));
 async function send(){if(busy)return;setError('');setNote('');if(!data.message.trim()||!messageFits(data)){setError('请填写正文，并调整到当前信笺可以容纳的长度。');return;}if(data.logoKind==='image'&&!logo){setError('请先上传角落标记图片。');return;}setBusy(true);try{const card={...data};const image=card.logoKind==='image'&&logo?await smallLogo(logo):undefined;const fingerprint=JSON.stringify([card,image]);if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,requestId:crypto.randomUUID(),ownerSecret:secret()};const attempt=pending.current;writeLocal('pending-letter',attempt);
 const response=await fetch('/api/letters',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({card,logo:image,requestId:attempt.requestId,ownerSecret:attempt.ownerSecret}),signal:AbortSignal.timeout(20000)});const payload=await response.json().catch(()=>null);if(!response.ok||!payload?.id)throw new Error(payload?.error||'信件尚未保存到云端，请稍后重试。');const item:Sent={id:payload.id,secret:attempt.ownerSecret,createdAt:payload.createdAt,title:card.title||'月球来信'};const next=[item,...sent.filter(x=>x.id!==item.id)];setSent(next);setResult(item);if(!writeLocal('sent-letters',next))setNote('本机无法保存入口，请务必复制并保存私密收件箱链接。');trackEvent('letter_created',{template:card.templateId});
 }catch(e){setError(e instanceof Error&&e.name==='TimeoutError'?'网络较慢，暂未确认保存结果。请重试，不会重复创建同一封信。':e instanceof Error?e.message:'寄信失败，请稍后重试。');}finally{setBusy(false);}}
 async function copy(item:Sent,privateLink=false){try{await navigator.clipboard.writeText(link(item,privateLink));setNote(privateLink?'私密收件箱链接已复制，请只保存给自己。':'好友拆信链接已复制。粘贴到微信聊天即可发送。');trackEvent(privateLink?'mailbox_link_copied':'letter_share_link_copied');}catch{setNote('请长按下面的链接复制。');}}
 return <section className="send-letter-panel" aria-labelledby="send-letter-title"><p className="eyebrow">SEND A LITTLE MOONLIGHT</p><h3 id="send-letter-title">装进信封，寄给重要的人</h3><p>把当前信笺保存到云端。好友打开链接、拆开信封，就能给你回信。</p><button className="postcard-main-action" disabled={disabled||busy} onClick={send}>{busy?'月球邮局正在封装…':'封好信封，生成分享链接'} <span>✉</span></button><small>持有分享链接的人都能读信和回复，请发送给信任的人。寄出后内容固定，继续编辑不会改变已寄出的信。</small>{error&&<p role="alert" className="send-error">{error}</p>}{note&&<p role="status">{note}</p>}
 {result&&<div className="send-letter-result"><strong>信已封好，等待你的好友拆开。</strong><label>发给好友的拆信链接<input readOnly value={link(result)} onFocus={e=>e.target.select()}/></label><button onClick={()=>copy(result)}>复制好友链接</button><p>在微信内也可以用右上角「…」转发当前拆信页面。</p><hr/><strong>留给自己的私密收件箱</strong><p>好友的回复会在这里出现。请保存这个链接，换手机或清除浏览器数据后可用它找回。不要发给好友。</p><label>私密收件箱链接<input readOnly value={link(result,true)} onFocus={e=>e.target.select()}/></label><div><button onClick={()=>copy(result,true)}>复制私密入口</button><Link to={`/mailbox/${result.id}/${result.secret}`}>打开我的收件箱 →</Link></div></div>}
 {sent.length>0&&<details className="sent-letter-list"><summary>我寄出的信 · {sent.length}</summary><p>这些私密入口只记录在当前浏览器。信件与回信保存在云端。</p>{sent.map(item=><Link key={item.id} to={`/mailbox/${item.id}/${item.secret}`}><span>{item.title}</span><small>{new Date(item.createdAt).toLocaleDateString('zh-CN')} · 查看回信 →</small></Link>)}</details>}
 </section>
}
