import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { get } from '../lib/storage';
import './home.css';
import LunarScene from '../components/scene/LunarScene';

const stops=[
 {id:'mooncake',number:'01',name:'月饼分拣站',english:'MOONCAKE EXPRESS',category:'动动手',duration:'60 秒',description:'让每一枚月饼，都找到对的收件人。看准口味，快快归盘。',action:'开始分拣',art:'cake',color:'orange'},
 {id:'quiz',number:'02',name:'月亮知识局',english:'LUNAR KNOWLEDGE',category:'动动脑',duration:'约 2 分钟',description:'八道小题，把诗词、传说和月亮的秘密装进口袋。',action:'抽一份题笺',art:'quiz',color:'blue'},
 {id:'persona',number:'03',name:'月下身份所',english:'FIND YOUR ORBIT',category:'动动脑',duration:'约 2 分钟',description:'十二个生活场景，发现与你心意相通的中秋角色。',action:'寻找我的身份',art:'persona',color:'mint'},
 {id:'wall',number:'04',name:'月光留言板',english:'WORDS TO THE MOON',category:'慢慢逛',duration:'随心停留',description:'把没来得及说的思念，轻轻留在这片月光里。',action:'写一句祝福',art:'wall',color:'lilac'},
 {id:'parkour',number:'05',name:'玉兔配送中',english:'SPECIAL DELIVERY',category:'动动手',duration:'约 1 分钟',description:'跟上兔子邮差的脚步，跳过障碍，收集沿途月光。',action:'出发去送信',art:'rabbit',color:'yellow'},
];
const filters=['全部站点','动动手','动动脑','慢慢逛'];
function StationArt({kind}:{kind:string}){return <svg viewBox="0 0 200 145" aria-hidden="true">{kind==='cake'?<><path d="M23 102h154" stroke="currentColor" strokeWidth="2"/><rect x="25" y="106" width="150" height="15" rx="7" fill="none" stroke="currentColor" strokeWidth="2"/>{[60,125].map((x,i)=><g key={x}><path d={`M${x-30} 52q0-13 13-13 0-13 13-10 12-8 20 3 14-2 17 13 13 6 7 19 8 11-4 21-2 14-17 12-11 10-22 0-16 2-19-12-13-8-8-21Z`} fill={i?'#e0c9a0':'#bda680'} stroke="currentColor" strokeWidth="2"/><circle cx={x+1} cy="65" r="23" fill="none" stroke="currentColor" strokeWidth="1.5"/><text x={x+1} y="72" textAnchor="middle" fontSize="22" fill="currentColor">月</text></g>)}</>:kind==='quiz'?<><path d="m36 40 58-13 69 14v84l-69-15-58 13Z" fill="#d8dce3" stroke="currentColor" strokeWidth="2"/><path d="M94 27v83M49 54l30-8m-30 21 30-8m-30 21 22-6" stroke="currentColor" strokeWidth="2"/><text x="126" y="88" textAnchor="middle" fontSize="46" fontFamily="sans-serif" fill="#637792">?</text><path d="m157 17 3-9 4 9 9 3-9 4-4 9-3-9-9-4Z" fill="#bda680"/></>:kind==='persona'?<><circle cx="100" cy="65" r="45" fill="#d8dce3" stroke="currentColor" strokeWidth="2"/><path d="M60 91q39-36 80 0" fill="#bda680"/><circle cx="100" cy="54" r="19" fill="#c9dfc4" stroke="currentColor" strokeWidth="2"/><path d="M80 106v24l20-10 20 10v-24" fill="#637792"/><path d="M30 41h16m-8-8v16m119 40h16m-8-8v16" stroke="currentColor" strokeWidth="2"/></>:kind==='wall'?<><rect x="25" y="38" width="115" height="71" rx="5" fill="#d8dce3" stroke="currentColor" strokeWidth="2"/><path d="m25 38 57 41 58-41M25 109l35-35m80 35-35-35" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M120 22h55v42h-30l-13 13V64h-12Z" fill="#637792"/><path d="M138 38q5-11 10-1 7-10 11-1 3 7-11 15-13-7-10-13" fill="#d8dce3"/></>:<><path d="M35 104h130m-110 12h72" stroke="currentColor" strokeWidth="2"/><path d="M106 51q-28-46-13-45 15 0 25 42m9 2q0-46 13-44 17 3-1 48" fill="#d8dce3" stroke="currentColor" strokeWidth="2"/><ellipse cx="124" cy="63" rx="32" ry="26" fill="#d8dce3" stroke="currentColor" strokeWidth="2"/><circle cx="133" cy="60" r="3" fill="currentColor"/><path d="M95 78q-38-2-40 25h68l-1-17" fill="#637792" stroke="currentColor" strokeWidth="2"/><path d="M90 82 104 99" stroke="#bda680" strokeWidth="6"/><path d="M39 54h36m-43 12h32m-20 13h17" stroke="currentColor" strokeWidth="2"/></>}</svg>}
export default function HomePage(){
 const [filter,setFilter]=useState('全部站点');const[stamps,setStamps]=useState<string[]>([]);
 useEffect(()=>{const sync=()=>{const value=get<unknown>('stamps',[]);setStamps(Array.isArray(value)?value.filter((v):v is string=>typeof v==='string'&&stops.some(stop=>stop.id===v)):[])};sync();window.addEventListener('moon:stamp',sync);window.addEventListener('storage',sync);window.addEventListener('focus',sync);return()=>{window.removeEventListener('moon:stamp',sync);window.removeEventListener('storage',sync);window.removeEventListener('focus',sync)}},[]);
 const scrollTo=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
 const next=stops.find(stop=>!stamps.includes(stop.id));const visible=stops.filter(stop=>filter==='全部站点'||stop.category===filter);
 return <main className="post-home"><header className="post-nav"><Link className="post-brand" to="/" aria-label="月球来信首页"><span className="post-brand-icon">↗</span><span>月球来信<small>MOON POST</small></span></Link><nav aria-label="首页导航"><button onClick={()=>scrollTo('post-map')}>探索地图</button><button onClick={()=>scrollTo('post-passport')}>游园护照 <span>{stamps.length}/5</span></button><Link to="/postcard">写封月信 <span>↗</span></Link></nav></header>
 <section className="post-hero"><div className="post-hero-copy"><div className="post-edition"><span/>2026 中秋特别营业 <i>VOL. 01</i></div><h1>把团圆，<br/>寄往<span>月亮。</span><svg viewBox="0 0 260 18" aria-hidden="true"><path d="M3 12Q130-6 254 7M15 17Q129 3 236 12" fill="none" stroke="currentColor" strokeWidth="3"/></svg></h1><p>欢迎来到离地球 384,400 公里的月球邮局。<br/>玩一会儿，慢一点，给想念的人留一封信。</p><div className="post-hero-actions"><button className="post-action" onClick={()=>scrollTo('post-map')}>开启月球漫游 <span>↗</span></button><Link className="post-text-link" to="/postcard">先寄一张明信片 <span>→</span></Link></div><div className="post-hero-note"><span className="post-avatar">☾</span><span>5 个奇遇站点 · 一份专属游园护照<br/><small>无需登录，随时出发</small></span></div></div><div className="post-hero-visual"><div className="post-coordinate">LUNAR ORBIT<br/>384,400 KM FROM HOME</div><LunarScene/><span className="post-open-label"><i/> 月光已抵达 · 等一封你的来信</span></div></section>
 <div className="post-ticker" aria-hidden="true"><span>月圆，是重逢的暗号</span><b>✳</b><span>YOUR WISH, OUR MISSION</span><b>✳</b><span>今天也请查收一点快乐</span><b>✳</b><span>FROM EARTH WITH LOVE</span></div>
 <section id="post-map" data-scene="1" className="post-map"><div className="post-section-heading"><div><p className="post-eyebrow">01 / EXPLORE THE MOON</p><h2>下一站，去哪儿？<span>↗</span></h2><p>不用按顺序，凭心情选一个。完成挑战，收集属于你的邮戳。</p></div><div className="post-map-count"><strong>05</strong><span>站点营业中</span></div></div><div className="post-filterbar"><div className="post-filters" role="group" aria-label="按玩法筛选">{filters.map(item=><button key={item} className={filter===item?'is-active':''} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}{item==='全部站点'&&<small>5</small>}</button>)}</div><span aria-live="polite">{visible.length} 个站点，等你靠岸</span></div><div className="post-station-grid">{visible.map(stop=><Link to={`/${stop.id}`} className={`post-station post-station-${stop.color}`} key={stop.id}><div className="post-station-top"><span>NO. {stop.number}</span><span className={stamps.includes(stop.id)?'post-status is-done':'post-status'}>{stamps.includes(stop.id)?'✓ 已收集邮戳':stop.duration}</span></div><div className="post-station-art"><StationArt kind={stop.art}/></div><p className="post-station-english">{stop.english}</p><h3>{stop.name}</h3><p className="post-station-description">{stop.description}</p><div className="post-station-bottom"><span>{stamps.includes(stop.id)?'再来体验一次':stop.action}</span><span>↗</span></div></Link>)}{filter==='全部站点'&&<Link className="post-station post-station-postcard" to="/postcard"><span className="post-bonus">BONUS DESTINATION</span><div className="post-postcard-art"><span>TO THE MOON</span><i>☾</i><b>见字如晤。</b><small>把想念，寄给你。</small></div><h3>有些话，写下来更好。</h3><p>挑一张月色，写一封月信。<br/>做一张属于你的中秋明信片。</p><div className="post-station-bottom"><span>制作我的明信片</span><span>↗</span></div></Link>}</div></section>
 <section id="post-passport" className="post-passport"><div className="post-passport-copy"><p className="post-eyebrow">02 / YOUR LUNAR PASSPORT</p><h2>来过月球，<br/>记得盖个章。</h2><p>{next?'你已经走过的路，月亮都记得。完成五个站点，收集一整份中秋快乐。':'五个站点全部抵达！你的月球旅程已圆满，给这趟旅行寄一张明信片吧。'}</p><Link className="post-action" to={next?`/${next.id}`:'/postcard'}>{next?`下一站：${next.name}`:'寄出圆满的月球来信'} <span>→</span></Link></div><div className="post-passport-card"><div className="post-passport-head"><span>月球漫游护照<small>LUNAR TRAVEL PASSPORT</small></span><b>{stamps.length}<i>/ 5</i></b></div><div className="post-passport-progress"><span style={{width:`${stamps.length/5*100}%`}}/></div><div className="post-stamps">{stops.map(stop=><Link key={stop.id} to={`/${stop.id}`} className={stamps.includes(stop.id)?'is-done':''} aria-label={`${stop.name}，${stamps.includes(stop.id)?'已完成':'待体验'}`}><span><i>{stamps.includes(stop.id)?'✓':stop.number}</i><b>{['月饼','知识','身份','月信','玉兔'][Number(stop.number)-1]}</b></span><small>{stamps.includes(stop.id)?'已盖章':'待抵达'}</small></Link>)}</div><p>旅程记录保存在当前浏览器 · 达成站点目标后盖章</p><div className="post-passport-serial"><span>PASSENGER / 月球旅人</span><span>MP—2026—0915</span></div></div></section>
 <footer className="post-footer"><Link className="post-brand" to="/"><span className="post-brand-icon">↗</span><span>月球来信<small>MOON POST</small></span></Link><p>愿每一份想念，都有回信。<span>FROM EARTH, WITH LOVE.</span></p><button onClick={()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}>返回地球入口 ↑</button></footer></main>
}
