import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { get } from '../lib/storage';
import './home.css';
import './station-cards.css';
import './home-visual-refresh.css';
import LunarScene from '../components/scene/LunarScene';
import PassportSection from '../components/PassportSection';

const stops=[
 {id:'mooncake',number:'01',name:'月饼分拣站',english:'MOONCAKE EXPRESS',category:'动动手',duration:'60 秒',description:'让每一枚月饼，都找到对的收件人。看准口味，快快归盘。',action:'开始分拣',art:'cake',color:'orange'},
 {id:'quiz',number:'02',name:'月亮知识局',english:'LUNAR KNOWLEDGE',category:'动动脑',duration:'约 2 分钟',description:'八道小题，把诗词、传说和月亮的秘密装进口袋。',action:'抽一份题笺',art:'quiz',color:'blue'},
 {id:'persona',number:'03',name:'月下身份所',english:'FIND YOUR ORBIT',category:'动动脑',duration:'约 2 分钟',description:'十二个生活场景，发现与你心意相通的中秋角色。',action:'寻找我的身份',art:'persona',color:'mint'},
 {id:'wall',number:'04',name:'月光留言板',english:'WORDS TO THE MOON',category:'慢慢逛',duration:'随心停留',description:'把没来得及说的思念，轻轻留在这片月光里。',action:'写一句祝福',art:'wall',color:'lilac'},
 {id:'parkour',number:'05',name:'玉兔配送中',english:'SPECIAL DELIVERY',category:'动动手',duration:'约 1 分钟',description:'跟上兔子邮差的脚步，跳过障碍，收集沿途月光。',action:'出发去送信',art:'rabbit',color:'yellow'},
];
const filters=['全部站点','动动手','动动脑','慢慢逛'];
export default function HomePage(){
 const [filter,setFilter]=useState('全部站点');const[stamps,setStamps]=useState<string[]>([]);
 useEffect(()=>{const sync=()=>{const value=get<unknown>('stamps',[]);setStamps(Array.isArray(value)?value.filter((v):v is string=>typeof v==='string'&&stops.some(stop=>stop.id===v)):[])};sync();window.addEventListener('moon:stamp',sync);window.addEventListener('storage',sync);window.addEventListener('focus',sync);return()=>{window.removeEventListener('moon:stamp',sync);window.removeEventListener('storage',sync);window.removeEventListener('focus',sync)}},[]);
 const scrollTo=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
 const visible=stops.filter(stop=>filter==='全部站点'||stop.category===filter);
 return <main className="post-home"><header className="post-nav"><Link className="post-brand" to="/" aria-label="月球来信首页"><span className="post-brand-icon">☾<i>✦</i></span><span>月球来信<small>MOON POST</small></span></Link><nav aria-label="首页导航"><button onClick={()=>scrollTo('post-map')}>探索地图</button><button onClick={()=>scrollTo('post-passport')}>游园护照 <span>{stamps.length}/5</span></button><Link to="/postcard">写封月信 <span>↗</span></Link></nav></header>
 <section className="post-hero"><div className="post-hero-landscape" aria-hidden="true"/><div className="post-hero-copy"><div className="post-edition"><span/>2026 中秋 · 月球特别企划</div><h1>把团圆，<br/>寄往<span>月亮。</span></h1><p>欢迎来到离地球 384,400 公里的月球邮局。<br/>玩一会儿，慢一点，给想念的人留一封信。</p><div className="post-hero-actions"><button className="post-action" onClick={()=>scrollTo('post-map')}>开启月球漫游 <span>→</span></button><Link className="post-text-link" to="/postcard"><span className="post-envelope" aria-hidden="true">✉</span>先寄一张明信片 <span className="post-secondary-arrow" aria-hidden="true">→</span></Link></div><div className="post-hero-note"><strong>384,400 <small>KM</small></strong><span>离地球很远 · 离想念很近</span></div></div><div className="post-hero-visual"><LunarScene/><img className="post-hero-rabbit" src="/images/moon/rabbit-letter-2026.png" alt="抱着月信、坐在月面岩石上的宇航员小白兔" draggable="false"/><span className="post-open-label"><i/> 左右上下拖动月球 · 看看月亮另一面</span></div><aside className="post-hero-aside" aria-label="月球旅程快捷入口"><span>把想念，<br/>写成一束光，<br/>送到月亮。</span><button onClick={()=>scrollTo('post-map')}><b>01</b> 探索月球</button><Link to="/postcard"><b>02</b> 写下月信</Link><button onClick={()=>scrollTo('post-passport')}><b>03</b> 寄往月球</button></aside><div className="post-hero-bottom"><span className="post-phases" aria-hidden="true">○ ◐ ◯ ◑ ●</span><span>月有圆缺 · 但爱从不缺席<br/><small>MOON ALWAYS LISTENS</small></span><button onClick={()=>scrollTo('post-map')}>↓ <span>向下探索</span></button></div></section>
 <div className="post-ticker" aria-hidden="true"><span>月圆，是重逢的暗号</span><b>✳</b><span>YOUR WISH, OUR MISSION</span><b>✳</b><span>今天也请查收一点快乐</span><b>✳</b><span>FROM EARTH WITH LOVE</span></div>
 <section id="post-map" data-scene="1" className="post-map"><div className="post-section-heading"><div><p className="post-eyebrow">01 / EXPLORE THE MOON</p><h2>下一站，去哪儿？<span>↗</span></h2><p>不用按顺序，凭心情选一个。完成挑战，收集属于你的邮戳。</p></div><div className="post-map-count"><strong>05</strong><span>站点营业中</span></div></div><div className="post-filterbar"><div className="post-filters" role="group" aria-label="按玩法筛选">{filters.map(item=><button key={item} className={filter===item?'is-active':''} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}{item==='全部站点'&&<small>5</small>}</button>)}</div><span aria-live="polite">{visible.length} 个站点，等你靠岸</span></div><div className="post-station-grid">{visible.map(stop=>{const done=stamps.includes(stop.id);return <Link to={`/${stop.id}`} className="post-station post-station-image" key={stop.id} aria-label={`${stop.name}，${done?'已收集邮戳，再来体验一次':`${stop.duration}，${stop.action}`}`}><img src={`/images/stations/${stop.id}.png`} alt="" width="1122" height="1402" loading="lazy" draggable="false"/>{done&&<span className="post-station-achieved">✓ 已收集邮戳</span>}</Link>})}{filter==='全部站点'&&<Link className="post-station post-station-image post-station-postcard" to="/postcard" aria-label="制作中秋明信片，有些话，写下来更好"><img src="/images/stations/postcard.png" alt="" width="1122" height="1402" loading="lazy" draggable="false"/></Link>}</div></section>
 <PassportSection stamps={stamps}/>
 <footer className="post-footer"><Link className="post-brand" to="/"><span className="post-brand-icon">☾<i>✦</i></span><span>月球来信<small>MOON POST</small></span></Link><p>愿每一份想念，都有回信。<span>FROM EARTH, WITH LOVE.</span></p><button onClick={()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}>返回地球入口 ↑</button></footer></main>
}
