import {useEffect,useMemo,useRef,useState,type CSSProperties,type FormEvent} from 'react';
import {Link,useParams} from 'react-router-dom';
import {trackEvent} from '../lib/analytics';
import {renderPostcard,templates,type PostcardData} from './postcard/render';
import './letters.css';

export type CloudLetter={id:string;card:PostcardData;logo?:string;createdAt:string};
export async function letterRequest<T>(url:string,options:RequestInit={}):Promise<T>{
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);
 try{const response=await fetch(url,{...options,cache:'no-store',signal:controller.signal,headers:{'Content-Type':'application/json',...options.headers}});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error?.message|| (typeof data?.error==='string'?data.error:'信件暂时未能送达，请稍后再试。'));if(!data)throw new Error('邮局暂时不可用，请稍后重试。');return data as T;}catch(error){if(error instanceof Error&&error.name==='AbortError')throw new Error('连接邮局超时，请检查网络后重试。');throw error;}finally{clearTimeout(timer);}
}
export function LetterArtwork({letter}:{letter:CloudLetter}){
 const svg=useMemo(()=>{const card=letter.card;const template=templates.find(t=>t.id===card?.templateId);if(!template)return '';if(!['moon','rabbit','festival'].includes(card.seal)||!['moon','rabbit','flower','rocket'].includes(card.stamp))return '';const logo=letter.logo&&/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(letter.logo)?letter.logo:undefined;return renderPostcard(card,template.asset,logo);},[letter]);
 return <div className={`letter-artwork ${letter.card.templateId==='osmanthus'?'letter-artwork-portrait':''}`} role="img" aria-label={`${letter.card.sender}寄给${letter.card.recipient}的明信片`} dangerouslySetInnerHTML={{__html:svg}}/>;
}
const letterStars=Array.from({length:58},(_,i)=>({left:`${((i*7919+137)%10000)/100}%`,top:`${((i*3571+251)%10000)/100}%`,size:i%9===0?3:1+(i%3)*.45,delay:-(i*1.37)%11,duration:3.5+(i%8)*.8}));
export function LetterShell({children}:{children:React.ReactNode}){return <main className="moon-letter-page"><div className="letter-random-stars" aria-hidden="true">{letterStars.map((star,i)=><i key={i} style={{left:star.left,top:star.top,width:star.size,height:star.size,animationDelay:`${star.delay}s`,animationDuration:`${star.duration}s`,'--star-tone':i%4===0?'#ffe1a8':'#d9ebff'} as CSSProperties}/>)}</div><header className="letter-brand"><Link to="/" aria-label="返回月球来信首页"><i className="letter-brand-icon" aria-hidden="true"/> <span>月球来信<small>MOON POST</small></span></Link><span>把温暖寄往月亮</span></header>{children}<footer className="letter-footer">同一轮月亮，照见每一份想念。<small>MOON POST · GOOD THINGS REACH FURTHER</small></footer></main>;}
export default function LetterPage(){
 const {id=''}=useParams();const [letter,setLetter]=useState<CloudLetter|null>(null);const [error,setError]=useState('');const [retry,setRetry]=useState(0);const [phase,setPhase]=useState<'sealed'|'opening'|'open'>('sealed');const [name,setName]=useState('');const [message,setMessage]=useState('');const [sending,setSending]=useState(false);const [sent,setSent]=useState(false);const [replyError,setReplyError]=useState('');const requestId=useRef(crypto.randomUUID());const openTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{let alive=true;setLetter(null);setError('');setPhase('sealed');setSent(false);setName('');setMessage('');setReplyError('');requestId.current=crypto.randomUUID();letterRequest<CloudLetter>(`/api/letters/${encodeURIComponent(id)}`).then(data=>{if(alive)setLetter(data);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;clearTimeout(openTimer.current);};},[id,retry]);
 const open=()=>{if(phase!=='sealed')return;trackEvent('letter_opened',{source:'recipient'});if(matchMedia('(prefers-reduced-motion: reduce)').matches){setPhase('open');return;}setPhase('opening');openTimer.current=setTimeout(()=>setPhase('open'),3100);};
 async function reply(event:FormEvent){event.preventDefault();if(sending||sent)return;if(!message.trim()){setReplyError('写下一句想说的话，再把回信交给玉兔。');return;}setSending(true);setReplyError('');try{await letterRequest(`/api/letters/${encodeURIComponent(id)}/replies`,{method:'POST',body:JSON.stringify({name:name.trim()||'赏月人',message:message.trim(),requestId:requestId.current})});setSent(true);trackEvent('reply_sent',{source:'recipient'});}catch(e){setReplyError(e instanceof Error?e.message:'回信暂未寄出，请重试。');}finally{setSending(false);}}
 return <LetterShell>{error?<section className="letter-state"><span className="letter-moon">☾</span><h1>这封信暂时无法打开</h1><p role="alert">{error}</p><button className="letter-gold" onClick={()=>setRetry(v=>v+1)}>重新连接邮局</button><Link to="/postcard">写一封自己的月球来信 →</Link></section>:!letter?<section className="letter-state" aria-live="polite"><span className="letter-moon">☾</span><h1>玉兔正在取信…</h1><p>让月光带路，稍等片刻。</p></section>:<>
 <section className="letter-intro"><p className="letter-kicker">A LETTER UNDER THE SAME MOON</p><h1>{phase==='open'?'月光，替我把话带到了':'你有一封月球来信'}</h1><p>致 <strong>{letter.card.recipient}</strong> · 来自 {letter.card.sender}</p></section>
 {phase!=='open'?<section className={`letter-unseal ${phase==='opening'?'is-opening':''}`} aria-label="待拆信封"><div className="letter-envelope"><div className="letter-envelope-sky" aria-hidden="true"/><div className="letter-envelope-paper" aria-hidden="true"><LetterArtwork letter={letter}/></div><div className="letter-envelope-back"/><div className="letter-envelope-art" aria-hidden="true"/><div className="letter-envelope-face"><small>TO THE MOON AND BEYOND</small><p>{letter.card.recipient} 亲启</p><span>MOON POST · 月球邮局</span></div><div className="letter-envelope-flap"/><button className="letter-wax" onClick={open} disabled={phase==='opening'} aria-label="点击月亮封蜡拆开信封"><img src="/images/letters/moon-wax.webp" alt="" draggable="false"/></button></div><p className="letter-unseal-hint" aria-live="polite">{phase==='opening'?'封蜡已开启，月光正在展开这封信…':'轻触月亮封蜡，拆开这份想念'}</p><button className="letter-text-button" onClick={()=>{if(phase==='sealed')trackEvent('letter_opened',{source:'skip'});clearTimeout(openTimer.current);setPhase('open');}}>直接阅读，跳过动画 →</button></section>:<div className="letter-reading"><LetterArtwork letter={letter}/><article className="letter-readable"><span className="letter-kicker">写给 {letter.card.recipient}</span><h2>{letter.card.title}</h2><p>{letter.card.message}</p><div className="letter-roam-row"><Link className="letter-roam-button" to="/" onClick={()=>trackEvent('letter_roam_clicked',{source:'recipient'})}>开启月球漫游 <span aria-hidden="true">→</span></Link></div></article>
 <section className="letter-reply">{sent?<div className="letter-success" role="status"><span>✧</span><h2>回信已寄出</h2><p>这份心意已放进寄件人的私密收件箱。<br/>等对方打开收件箱，就能读到你的回复。</p><Link to="/postcard" className="letter-gold">我也想寄一封信 →</Link></div>:<><span className="letter-kicker">SEND A LITTLE MOONLIGHT BACK</span><h2>让想念，有来有回</h2><p>回信仅供寄件人在私密收件箱查看。</p><form onSubmit={reply}><label>你的署名 <span>选填</span><input maxLength={20} value={name} onChange={e=>{setName(e.target.value);requestId.current=crypto.randomUUID();}} placeholder="留个名字，或做一位赏月人" autoComplete="off" disabled={sending}/></label><label>想对寄件人说的话<textarea maxLength={500} required rows={5} value={message} onChange={e=>{setMessage(e.target.value);requestId.current=crypto.randomUUID();}} placeholder="收到你的月光了，我想对你说……" disabled={sending}/></label><div className="letter-form-bottom"><span>{message.length}/500</span><button className="letter-gold" disabled={sending}>{sending?'玉兔正在送信…':'把回信寄给 TA ↗'}</button></div>{replyError&&<p className="letter-error" role="alert">{replyError}</p>}</form></>}</section></div>}
 </>}</LetterShell>;
}
