import {useCallback,useEffect,useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {trackEvent} from '../lib/analytics';
import {get as readLocal,set as writeLocal} from '../lib/storage';
import {LetterArtwork,LetterShell,letterRequest,type CloudLetter} from './LetterPage';
import './letters.css';
type Inbox={letter:CloudLetter;replies:{id:string;name:string;message:string;createdAt:string}[]};
function date(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'});}
export default function MailboxPage(){
 const {id='',secret=''}=useParams();const [inbox,setInbox]=useState<Inbox|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [notice,setNotice]=useState('');const [revoked,setRevoked]=useState(false);const [confirmRevoke,setConfirmRevoke]=useState(false);const [deleting,setDeleting]=useState(false);const [checked,setChecked]=useState('');const alive=useRef(true);const running=useRef<number|null>(null);const generation=useRef(0);
 const load=useCallback(async()=>{const version=generation.current;if(running.current===version)return;running.current=version;setLoading(true);try{const data=await letterRequest<Inbox>(`/api/letters/${encodeURIComponent(id)}/inbox`,{headers:{Authorization:`Bearer ${secret}`}});if(alive.current&&generation.current===version){setInbox(data);setError('');setChecked(new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}));}}catch(e){if(alive.current&&generation.current===version)setError(e instanceof Error?e.message:'暂时无法取回信，请稍后重试。');}finally{if(running.current===version)running.current=null;if(alive.current&&generation.current===version)setLoading(false);}},[id,secret]);
 useEffect(()=>{setInbox(null);setError('');setRevoked(false);setNotice('');setChecked('');setConfirmRevoke(false);},[id,secret]);
 useEffect(()=>{generation.current++;alive.current=!revoked;if(revoked)return;void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},20000);const onVisible=()=>{if(document.visibilityState==='visible')void load();};document.addEventListener('visibilitychange',onVisible);return()=>{alive.current=false;generation.current++;clearInterval(timer);document.removeEventListener('visibilitychange',onVisible);};},[load,revoked]);
 async function copy(kind:'private'|'share'){const url=`${location.origin}${location.pathname}#/${kind==='private'?`mailbox/${id}/${secret}`:`letter/${id}`}`;try{await navigator.clipboard.writeText(url);setNotice(kind==='private'?'私密收件箱链接已复制，请只保存给自己。':'好友拆信链接已复制，可以粘贴给微信好友。');trackEvent(kind==='private'?'mailbox_link_copied':'letter_share_link_copied',{source:'mailbox'});}catch{setNotice('浏览器未允许复制，请长按下方链接选择复制。');}}
 async function revoke(){if(deleting)return;setDeleting(true);try{await letterRequest(`/api/letters/${encodeURIComponent(id)}/inbox`,{method:'DELETE',headers:{Authorization:`Bearer ${secret}`}});setRevoked(true);setConfirmRevoke(false);const saved=readLocal<{id:string}[]>('sent-letters',[]);if(Array.isArray(saved))writeLocal('sent-letters',saved.filter(item=>item.id!==id));trackEvent('letter_revoked',{source:'mailbox'});}catch(e){setError(e instanceof Error?e.message:'撤回失败，请重试。');}finally{setDeleting(false);}}
 return <LetterShell>{revoked?<section className="letter-state"><span className="letter-moon">☾</span><h1>信件已撤回</h1><p>好友的拆信链接已失效，原信与回信已删除。</p><Link className="letter-gold" to="/postcard">再写一封月球来信 →</Link></section>:<><section className="letter-intro"><p className="letter-kicker">YOUR PRIVATE MOON MAILBOX</p><h1>月光收件箱</h1><p>寄出去的想念，会在这里收到回音。</p></section><aside className="letter-private-note"><strong>这是你的私密入口，请不要转发给好友。</strong><p>保存此页面链接，换设备也能取回信。拥有此链接的人可以阅读回复和撤回信件。页面打开时会自动检查新回信，不会发送微信提醒。</p><button className="letter-text-button" onClick={()=>void copy('private')}>复制我的私密收件箱链接 ↗</button></aside>{notice&&<p className="letter-notice" role="status">{notice}</p>}{error&&<p className="letter-error" role="alert">{error}</p>}
 <div className="letter-inbox-toolbar"><h2>收到的回信 {inbox&&<span>{inbox.replies.length}</span>}</h2><button className="letter-outline" disabled={loading} onClick={()=>void load()}>{loading?'取信中…':'刷新回信'}</button></div><p className="letter-check-time">{checked?`上次检查 ${checked} · 每 20 秒自动取信`:'正在连接月球邮局'}</p>
 {inbox?<><section className="letter-replies" aria-live="polite">{inbox.replies.length?inbox.replies.map(reply=><article className="letter-received" key={reply.id}><header><strong>{reply.name}</strong><time>{date(reply.createdAt)}</time></header><p>{reply.message}</p><span>☾ 月光已送达</span></article>):<div className="letter-empty"><span>✉</span><h3>还在等一封回信</h3><p>将下面的好友链接发给对方。<br/>对方拆开信封并回复后，心意就会来到这里。</p></div>}</section><details className="letter-original"><summary>你寄出的明信片 · 致 {inbox.letter.card.recipient}</summary><LetterArtwork letter={inbox.letter}/></details><section className="letter-share-again"><h2>把信封交给好友</h2><p>复制这个链接发给好友，对方即可拆信和回复。持有好友链接的人都可以阅读原信。</p><input aria-label="好友拆信链接" readOnly value={`${location.origin}${location.pathname}#/letter/${id}`} onFocus={e=>e.target.select()}/><button className="letter-gold" onClick={()=>void copy('share')}>复制好友拆信链接 ↗</button><details><summary>保存私密收件箱链接</summary><input aria-label="私密收件箱链接" readOnly value={`${location.origin}${location.pathname}#/mailbox/${id}/${secret}`} onFocus={e=>e.target.select()}/></details></section><section className="letter-revoke">{confirmRevoke?<><p>撤回会删除这封信及全部回信，好友链接也会失效，无法恢复。确定撤回吗？</p><button className="letter-outline" disabled={deleting} onClick={()=>void revoke()}>{deleting?'正在撤回…':'确定撤回'}</button><button className="letter-text-button" disabled={deleting} onClick={()=>setConfirmRevoke(false)}>保留信件</button></>:<button className="letter-text-button" onClick={()=>setConfirmRevoke(true)}>撤回这封信</button>}</section></>:!loading&&<Link to="/postcard" className="letter-text-button">返回明信片工坊 →</Link>}</>}</LetterShell>;
}
