import {useCallback,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import MooncakeSprite from '../components/game/MooncakeSprite';
import {award} from '../lib/storage';
import {recordMooncake} from '../lib/journey';
import {startActivity,finishActivity} from '../lib/analytics';
import './mooncake.css';

const tastes=['白莲蓉','蛋黄莲蓉','经典五仁','红豆沙','抹茶冰皮'];
const notes=['清甜温润','咸香流油','香脆果仁','软糯细腻','清爽弹牙'];
const difficulties={
 easy:{label:'简单',detail:'慢速 · 少量出饼',speed:8,interval:3.6,initial:1,limit:3},
 medium:{label:'中等',detail:'匀速 · 连续出饼',speed:11,interval:2.5,initial:2,limit:4},
 hard:{label:'困难',detail:'快速 · 密集出饼',speed:15,interval:1.75,initial:3,limit:5},
} as const;
type Difficulty=keyof typeof difficulties;
type Cake={id:number;type:number;x:number};
type SortedCake=Cake&{elapsed:number;points:number};
type Game={cakes:Cake[];sorted:SortedCake[];score:number;combo:number;max:number;correct:number;missed:number;time:number};
const fresh=():Game=>({cakes:[],sorted:[],score:0,combo:0,max:0,correct:0,missed:0,time:60});

export default function MooncakePage(){
 const [difficulty,setDifficulty]=useState<Difficulty>('easy');
 const config=difficulties[difficulty];
 const [game,setGame]=useState<Game>(fresh);
 const [phase,setPhase]=useState<'ready'|'playing'|'over'>('ready');
 const [book,setBook]=useState(false),[paused,setPaused]=useState(false);
 const [feedback,setFeedback]=useState(''),[flash,setFlash]=useState<number|null>(null);
 const [best,setBest]=useState(()=>{try{return Number(localStorage.getItem('moon-garden:mooncake-best'))||0}catch{return 0}});
 const data=useRef<Game>(fresh()),nextId=useRef(0),spawnElapsed=useRef(0);
 const feedbackTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),flashTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const notify=useCallback((message:string)=>{setFeedback(message);clearTimeout(feedbackTimer.current);feedbackTimer.current=setTimeout(()=>setFeedback(''),1600)},[]);
 useEffect(()=>()=>{clearTimeout(feedbackTimer.current);clearTimeout(flashTimer.current)},[]);
 const start=()=>{startActivity('mooncake',{difficulty});setPaused(false);spawnElapsed.current=0;data.current=fresh();data.current.cakes=Array.from({length:config.initial},(_,i)=>({id:nextId.current++,type:Math.floor(Math.random()*5),x:(config.initial===1?76:96)-(config.initial-1-i)*26}));setGame({...data.current});setFeedback('');setFlash(null);clearTimeout(feedbackTimer.current);clearTimeout(flashTimer.current);setPhase('playing')};
 const sort=useCallback((type:number)=>{if(phase!=='playing'||book||paused)return;const g=data.current;if(!g.cakes.length){notify('下一枚月饼马上就来');return}const target=g.cakes[0];setFlash(type);clearTimeout(flashTimer.current);flashTimer.current=setTimeout(()=>setFlash(null),220);if(target.type===type){g.cakes.shift();g.combo++;g.correct++;g.max=Math.max(g.max,g.combo);const points=10+Math.min(20,Math.floor(g.combo/5)*5);g.score+=points;g.sorted.push({...target,elapsed:0,points});notify(g.combo>1?'归盘成功！'+g.combo+' 连击 · +'+points:'完美归盘 · +'+points)}else{g.score=Math.max(0,g.score-5);g.combo=0;g.missed++;notify('这枚是'+tastes[target.type]+'哦 · −5')}setGame({...g,cakes:[...g.cakes]})},[phase,book,paused,notify]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,select,[contenteditable]:not([contenteditable="false"])'))return;if(e.code==='Space'&&phase==='playing'&&!book){e.preventDefault();if(!e.repeat)setPaused(value=>!value);return}if(e.key==='Escape'){setBook(false);return}if(/^[1-5]$/.test(e.key)&&!e.repeat){e.preventDefault();sort(Number(e.key)-1)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[sort,phase,book]);
 useEffect(()=>{const hide=()=>{if(document.hidden&&phase==='playing')setPaused(true)};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[phase]);
 useEffect(()=>{if(phase!=='playing'||book||paused)return;let raf=0,last=performance.now();const tick=(now:number)=>{if(document.hidden){setPaused(true);return}const delta=Math.max(0,Math.min((now-last)/1000,.1));last=now;const g=data.current;g.time=Math.max(0,g.time-delta);spawnElapsed.current+=delta;g.sorted=g.sorted.map(c=>({...c,elapsed:c.elapsed+delta})).filter(c=>c.elapsed<.42);g.cakes=g.cakes.map(c=>({...c,x:c.x-delta*config.speed}));if(spawnElapsed.current>=config.interval&&g.cakes.length<config.limit){spawnElapsed.current=0;g.cakes.push({id:nextId.current++,type:Math.floor(Math.random()*5),x:100})}while(g.cakes[0]?.x<0){g.cakes.shift();g.score=Math.max(0,g.score-5);g.combo=0;g.missed++;notify('漏掉一枚月饼 · −5')}setGame({...g,cakes:[...g.cakes]});if(g.time<=0){finishActivity('mooncake',{outcome:'completed',score:g.score,correct:g.correct,missed:g.missed,max_combo:g.max,difficulty});setPhase('over');const record=Math.max(best,g.score);setBest(record);recordMooncake({score:g.score,correct:g.correct,missed:g.missed,maxCombo:g.max,difficulty,at:new Date().toISOString()});try{localStorage.setItem('moon-garden:mooncake-best',String(record))}catch{}if(g.correct>0)award('mooncake');return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[phase,book,paused,best,notify,config,difficulty]);

 return <div className={'mc-page '+(paused||book?'mc-motion-paused':'')}>
  <section className="mc-hero" aria-labelledby="mc-title"><div className="mc-hero-copy"><p className="mc-hero-kicker"><span>✦</span> 01 / MOONCAKE EXPRESS</p><h2 id="mc-title">月饼分拣站</h2><p>月饼正从广寒宫出炉！看准传送带上<br className="mc-wide-only"/>最靠左的一枚，点击对应口味的玉盘，送它回家。</p></div><span className="mc-hero-script">把美味，送回月亮 <i>✦</i></span><div className="mc-hero-quote" aria-hidden="true">每一枚月饼<br/>都有回家的方向。<span>GOOD THINGS<br/>REACH FURTHER</span></div></section>
  <section className="mc-stats" aria-label="游戏成绩与操作"><div className="mc-stat"><span className="mc-stat-icon">✦</span><p>当前得分<strong>{game.score}</strong></p></div><div className="mc-stat"><span className="mc-stat-icon">♨</span><p>连续归盘<strong>{game.combo} <small>/ MAX {game.max}</small></strong></p></div><div className="mc-stat"><span className="mc-stat-icon">◷</span><p>剩余时间<strong className={game.time<10?'mc-urgent':''}>{Math.ceil(game.time)} <small>秒</small></strong></p></div><div className="mc-stat mc-stat-difficulty"><span className="mc-stat-icon">ϟ</span><label htmlFor="mc-difficulty-select">出饼难度<select id="mc-difficulty-select" value={difficulty} disabled={phase==='playing'} onChange={e=>setDifficulty(e.target.value as Difficulty)}>{(Object.keys(difficulties) as Difficulty[]).map(mode=><option key={mode} value={mode}>{difficulties[mode].label}</option>)}</select></label></div>{phase==='ready'?<button className="mc-stats-action" onClick={start}>启程分月饼 <span>▶</span></button>:phase==='playing'?<button className="mc-stats-action mc-stats-action-quiet" onClick={()=>setPaused(value=>!value)} aria-pressed={paused}>{paused?'继续挑战':'暂停挑战'} <span>{paused?'▶':'Ⅱ'}</span></button>:<button className="mc-stats-action" onClick={start}>再来一盘 <span>↗</span></button>}</section>
  <section className="mc-workshop" aria-label="月饼分拣游戏"><header className="mc-workshop-head"><h3><span>✿</span> 月饼传送带 <small>/ MOONCAKE LINE</small></h3><div><button className="mc-book-button" onClick={()=>setBook(true)}>月饼图鉴 ↗</button><span className="mc-workshop-status">{phase==='playing'?paused?'已暂停':'正在出饼':phase==='over'?'本轮结束':'等待开工'}</span></div></header><div className="mc-stage-row"><div className="mc-conveyor"><div className="mc-belt-rails" aria-hidden="true"/><div className={'mc-belt '+(phase==='playing'&&!book&&!paused?'mc-moving':'')} style={{animationDuration:(24/config.speed)+'s'}} aria-hidden="true"/><div className="mc-sort-gate" aria-hidden="true"><span>当前待分拣</span><b>➜</b></div>{game.cakes.map(c=><div key={c.id} className="mc-travel-cake" style={{left:c.x+'%'}}><MooncakeSprite type={c.type} size={106}/><span className={'mc-cake-label mc-flavor-'+c.type}>{tastes[c.type]}</span></div>)}{game.sorted.map(c=>{const progress=Math.min(1,c.elapsed/.42);return <div key={c.id} aria-hidden="true" className="mc-travel-cake mc-sorting-cake" style={{left:c.x+'%',opacity:1-progress,transform:'translate(-50%, '+(-52*progress)+'px) scale('+(1-.65*progress)+') rotate('+(progress*14)+'deg)'}}><MooncakeSprite type={c.type} size={106}/><span className="mc-sort-spark">+{c.points} ✦</span></div>})}{phase==='ready'&&<div className="mc-idle-cakes" aria-hidden="true">{[0,2,3,4,1].map((type,i)=><span key={i}><MooncakeSprite type={type} size={98}/></span>)}</div>}{phase==='playing'&&paused&&<div className="mc-pause-status" role="status"><strong>挑战已暂停</strong><p>计时和传送带都已停下。</p><button onClick={()=>setPaused(false)}>继续挑战 · 空格</button></div>}</div><aside className="mc-stage-quote" aria-hidden="true">让每一枚月饼<br/>找到回家的路<span>TO A<br/>BRIGHTER MOON ✦</span></aside></div><div className="mc-live-line"><span className="mc-current-target" role="status" aria-live="polite">{phase==='playing'?game.cakes[0]?'最靠左：'+tastes[game.cakes[0].type]+' · 选 '+(game.cakes[0].type+1)+' 号玉盘':'下一枚月饼即将送达…':phase==='over'?'本轮归盘 '+game.correct+' 枚 · 最高连击 '+game.max:'看准最靠左的一枚，投入对应口味的玉盘'}</span><span className="mc-feedback" role="status" aria-live="polite">{feedback||config.label+'模式 · 连击可以赢取额外分数'}</span></div><div className="mc-plates" aria-label="选择月饼玉盘">{tastes.map((name,i)=><button key={name} type="button" disabled={phase!=='playing'||book||paused} onClick={()=>sort(i)} className={'mc-plate mc-flavor-'+i+(flash===i?' mc-selected':'')} aria-label={(i+1)+' 号玉盘，'+name}><kbd>{i+1}</kbd><div className="mc-plate-dish"><MooncakeSprite type={i} size={88}/></div><h4>{name}</h4><span>{notes[i]}</span></button>)}</div></section>
  <div className="mc-bottom-note"><div className="mc-shortcut"><span className="mc-helper-icon">▦</span><span><strong>键盘快捷键</strong><small>按 <kbd>1–5</kbd> 将月饼分拣到对应口味的玉盘</small></span></div><p>“ 小小的一枚月饼，装着大大的团圆。 ”<small>MOON POST · 本机最高 {best} 分</small></p><div className="mc-helper-actions"><button onClick={()=>phase==='playing'?setPaused(value=>!value):start()}><b>{phase==='playing'?paused?'▶':'Ⅱ':'↻'}</b><span>{phase==='playing'?paused?'继续挑战':'暂停挑战':'开始挑战'}<small>{phase==='playing'?'空格键':'60 秒限时'}</small></span></button><button onClick={()=>setBook(true)}><b>?</b><span>游戏说明<small>如何玩?</small></span></button></div></div>
  {phase==='over'&&<div className="mc-overlay"><section className="mc-dialog" role="dialog" aria-modal="true" aria-labelledby="mc-dialog-title"><div className="mc-dialog-art"><MooncakeSprite type={0} size={108}/><span>✦</span></div><p className="mc-eyebrow">01 / MOONCAKE EXPRESS</p><h2 id="mc-dialog-title">满盘月色，收工啦</h2><div className="mc-result"><strong>{game.score}<small>分</small></strong><p>正确归盘 {game.correct} 枚 · 最高 {game.max} 连击</p></div><p>{game.correct>0?'月饼邮戳已收集，已记入游园护照。':'再试一次，找到月饼的正确归宿。'}</p><button className="mc-start" onClick={start}>再来一盘 <span>→</span></button><nav className="mc-result-links" aria-label="挑战完成后的选择"><Link to="/quiz">下一站 · 月亮知识局 →</Link><Link to="/?section=pavilions">回探索地图</Link></nav></section></div>}
  {book&&<div className="mc-overlay mc-book-overlay" onClick={()=>setBook(false)}><section className="mc-dialog mc-book-dialog" role="dialog" aria-modal="true" aria-labelledby="mc-book-title" onClick={e=>e.stopPropagation()}><button className="mc-close" aria-label="关闭月饼图鉴" onClick={()=>setBook(false)}>×</button><p className="mc-eyebrow">广寒工坊 · 口味小笺</p><h2 id="mc-book-title">一饼一味，一口团圆</h2><p>看准传送带上最靠左的一枚，点击相同口味的玉盘。限时 60 秒，归盘 +10 分；错分或漏单扣 5 分，连击还能额外加分。</p><div className="mc-book-grid">{tastes.map((taste,i)=><div key={taste}><MooncakeSprite type={i} size={82}/><h3>{taste}</h3><p>{notes[i]}</p><kbd>按键 {i+1}</kbd></div>)}</div><p>游戏中查阅图鉴时，计时和传送带都会暂停。</p><button className="mc-start" onClick={()=>setBook(false)}>记住了，回到工坊</button></section></div>}
 </div>
}
