import { useState } from 'react';
import { Link } from 'react-router-dom';
import { PERSONAS, SCENES } from '../data/content';
import { award, set } from '../lib/storage';
import { JadeRabbit, ChangE } from '../components/scene/Mascots';
import './shared-activities.css';
export default function PersonaPage(){
 const [phase,setPhase]=useState<'ready'|'playing'|'result'>('ready'),[index,setIndex]=useState(0),[answers,setAnswers]=useState<number[]>([]),[result,setResult]=useState(0);
 const selected=answers[index];
 const start=()=>{setAnswers([]);setIndex(0);setPhase('playing')};
 const choose=(choice:number)=>setAnswers(previous=>{const next=[...previous];next[index]=choice;return next});
 const next=()=>{if(selected===undefined)return;if(index<SCENES.length-1){setIndex(value=>value+1);return}const tally=Array(6).fill(0) as number[];answers.forEach((option,i)=>{tally[SCENES[i][1][option][1]]++});const max=Math.max(...tally);const winners=tally.map((n,i)=>n===max?i:-1).filter(i=>i>=0);const winner=winners.find(id=>id===SCENES[0][1][answers[0]][1])??winners[0];setResult(winner);set('persona-result',{id:winner,answers,date:new Date().toISOString()});award('persona');setPhase('result')};
 const persona=PERSONAS[result];
 return <main className="activity-page persona-page"><div className="activity-ambient-moon"/><div className="activity-topline"><span>每个人心里，都住着一轮不一样的月亮。</span><span>十二问 · 六种月下身份</span></div>{phase==='ready'?<section className="activity-panel activity-welcome"><div className="activity-persona-pair"><ChangE/><JadeRabbit/></div><p className="activity-eyebrow">第三摊 · 月下签铺</p><h1>你是哪一种中秋人格？</h1><p className="activity-lead">凭直觉选择十二个小场景，<br/>让月亮告诉你，今夜谁与你心意相通。</p><div className="activity-facts"><span>十二个生活场景</span><span>没有标准答案</span><span>约 2 分钟</span></div><button className="activity-primary" onClick={start}>借月光，认识自己 <span>→</span></button><p className="activity-fine">仅供节日娱乐与自我探索，不是心理诊断。</p></section>:phase==='playing'?<section className="activity-panel activity-question" aria-labelledby="persona-question"><div className="activity-progress-heading"><span>随心作答 · 不必思考太久</span><span>第 <b>{String(index+1).padStart(2,'0')}</b> / 12 问</span></div><div className="activity-progress-track"><span style={{width:`${(index+1)/12*100}%`}}/></div><p className="activity-eyebrow">月亮想听你的答案</p><h1 id="persona-question">{SCENES[index][0]}</h1><div className="activity-options">{SCENES[index][1].map(([option],i)=><button key={`${index}-${i}`} onClick={()=>choose(i)} aria-pressed={selected===i} className={selected===i?'is-selected':''}><span className="activity-option-letter">{String.fromCharCode(65+i)}</span><span>{option}</span><i>{selected===i?'✓':'↗'}</i></button>)}</div><div className="activity-question-bottom"><button className="activity-back" disabled={index===0} onClick={()=>setIndex(value=>value-1)}>← 上一问</button><button className="activity-primary" disabled={selected===undefined} onClick={next}>{index===11?'揭晓我的月下身份':'下一问'} <span>→</span></button></div><p className="activity-fine">答案无对错。返回上一问时，会保留你的选择。</p></section>:<section className="activity-panel activity-result persona-result"><p className="activity-eyebrow">月下签铺 · 你的专属月光</p><div className="activity-persona-symbol">{result===0?<ChangE/>:result===1?<JadeRabbit/>:<span>{persona[4]}</span>}</div><p className="activity-result-kicker">今夜，与你相伴的是</p><h1>{persona[0]} <span>· {persona[1]}</span></h1><p className="activity-persona-description">{persona[2]}</p><div className="activity-persona-tip"><span>月亮给你的小纸条</span><p>{persona[3]}</p></div><div className="activity-stamp-notice">✧ 月下签铺游园灯已点亮</div><div className="activity-result-actions"><button className="activity-primary" onClick={start}>重新抽一支签 <span>↻</span></button><Link className="activity-secondary" to="/?section=pavilions">返回探索地图</Link></div><p className="activity-fine">趣味结果由本次选择生成，仅供娱乐 · 记录保存在当前浏览器</p></section>}</main>
}
