import { useState } from 'react';
import { Link } from 'react-router-dom';
import { QUESTIONS } from '../data/content';
import { award, get, set } from '../lib/storage';
import './shared-activities.css';
const makeRound=()=>{const pool=[...QUESTIONS];for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return pool.slice(0,8)};
export default function QuizPage(){
 const [round,setRound]=useState(makeRound),[phase,setPhase]=useState<'ready'|'playing'|'result'>('ready'),[index,setIndex]=useState(0),[chosen,setChosen]=useState<number|null>(null),[correct,setCorrect]=useState(0),[best,setBest]=useState(()=>get<number>('quiz-best',0));
 const question=round[index];
 const start=()=>{setRound(makeRound());setIndex(0);setChosen(null);setCorrect(0);setPhase('playing')};
 const answer=(option:number)=>{if(chosen!==null)return;setChosen(option);if(option===question[2])setCorrect(value=>value+1)};
 const next=()=>{if(chosen===null)return;if(index<round.length-1){setIndex(value=>value+1);setChosen(null)}else{const record=Math.max(best,correct);setBest(record);set('quiz-best',record);set('quiz-result',{correct,total:8,date:new Date().toISOString()});award('quiz');setPhase('result')}};
 return <main className="activity-page quiz-page"><div className="activity-ambient-moon"/><div className="activity-topline"><span>桂花树下，借一盏灯读懂中秋。</span><span>本机最佳 <b>{best} / 8</b></span></div>
 {phase==='ready'?<section className="activity-panel activity-welcome"><div className="activity-seal">知</div><p className="activity-eyebrow">第二摊 · 桂花书院</p><h1>月下有问，灯中有答</h1><p className="activity-lead">从一行诗、一缕桂香，到月亮的小秘密。<br/>八道趣味小题，邀你与中秋多一分熟悉。</p><div className="activity-facts"><span>八道随机题</span><span>不限作答时间</span><span>每题附小解</span></div><button className="activity-primary" onClick={start}>提灯，开始答题 <span>→</span></button><p className="activity-fine">完成一轮，即可点亮「桂花书院」游园灯。</p></section>:phase==='playing'?<section className="activity-panel activity-question" aria-labelledby="quiz-question"><div className="activity-progress-heading"><span>中秋知识小笺</span><span>第 <b>{String(index+1).padStart(2,'0')}</b> / 08 题</span></div><div className="activity-progress-track"><span style={{width:`${(index+(chosen!==null?1:0))/8*100}%`}}/></div><p className="activity-eyebrow">一题一风雅 · 已答对 {correct} 题</p><h1 id="quiz-question">{question[0]}</h1><div className="activity-options">{question[1].map((option,i)=><button key={`${index}-${i}`} onClick={()=>answer(i)} disabled={chosen!==null} className={`${chosen!==null&&i===question[2]?'is-correct':''} ${chosen===i&&i!==question[2]?'is-wrong':''}`}><span className="activity-option-letter">{String.fromCharCode(65+i)}</span><span>{option}</span><i>{chosen!==null&&i===question[2]?'✓':chosen===i?'×':'↗'}</i></button>)}</div>{chosen!==null&&<div className={`activity-explanation ${chosen===question[2]?'is-correct':'is-wrong'}`} role="status"><strong>{chosen===question[2]?'答对了，月光为你点亮！':'差一点点，来认识这个中秋小知识。'}</strong><p>{question[3]}</p></div>}<div className="activity-question-bottom"><span>{chosen===null?'选一个答案，听听月亮的解释。':'读懂一段来历，也是游园的收获。'}</span><button className="activity-primary" disabled={chosen===null} onClick={next}>{index===7?'查看我的成绩':'下一题'} <span>→</span></button></div></section>:<section className="activity-panel activity-result"><p className="activity-eyebrow">桂花书院 · 今夜结笺</p><div className="activity-seal">{correct>=6?'魁':'知'}</div><h1>{correct>=7?'满腹月光，才气盈袖':correct>=4?'提灯问月，亦有所得':'月下新知，已入行囊'}</h1><div className="activity-score"><strong>{correct}</strong><span>/ 8 题</span></div><p className="activity-lead">{correct>=6?'诗词、传说与月亮的秘密，你都记在心里。':'不必题题满分，今夜又与中秋熟悉了一些。'}</p><div className="activity-stamp-notice">✧ 桂花书院游园灯已点亮</div><div className="activity-result-actions"><button className="activity-primary" onClick={start}>再抽一笺 <span>↻</span></button><Link className="activity-secondary" to="/?section=pavilions">返回探索地图</Link></div><p className="activity-fine">成绩与游园印记保存在当前浏览器。</p></section>}</main>
}
