import { useState } from 'react';
import { award, get, set } from '../lib/storage';
import './wall.css';
type Wish={id:string;name:string;text:string;date:number};
const demos:Wish[]=[{id:'demo-1',name:'长安客',text:'愿人长久，千里共婵娟。',date:0},{id:'demo-2',name:'桂花小兔',text:'愿所有奔赴，都有团圆。',date:0},{id:'demo-3',name:'月下归人',text:'今夜月明，把想念说给月亮听。',date:0}];
const quick=['月圆人团圆，好事常相伴。','愿所念之人，平安喜乐。','但愿人长久，千里共婵娟。','愿你的每一份努力，都有圆满。'];
export default function WallPage(){
 const [wishes,setWishes]=useState<Wish[]>(()=>{const saved=get<unknown>('wishes',[]);return Array.isArray(saved)?saved.filter((w):w is Wish=>!!w&&typeof w==='object'&&typeof w.id==='string'&&typeof w.text==='string'&&typeof w.name==='string'&&typeof w.date==='number'):[]}),[name,setName]=useState(''),[message,setMessage]=useState(''),[feedback,setFeedback]=useState(''),[deleteId,setDeleteId]=useState<string|null>(null);
 const demo=wishes.length===0, shown=demo?demos:wishes;
 function submit(e:React.FormEvent){e.preventDefault();if(!message.trim()){setFeedback('先写下一句想送给月亮的话吧。');return}const wish={id:crypto.randomUUID(),name:name.trim()||'一位赏月人',text:message.trim().slice(0,40),date:Date.now()};const next=[wish,...wishes];setWishes(next);set('wishes',next);award('wall');setMessage('');setFeedback('已点亮一盏心愿灯，祝福保存在当前浏览器。')}
 function remove(id:string){const next=wishes.filter(w=>w.id!==id);setWishes(next);set('wishes',next);setDeleteId(null);setFeedback('这条本机留言已删除。')}
 return <main className="wall-page"><section className="wall-sky" aria-label="月下心愿灯"><div className="wall-stars"/><div className="wall-moon"><span>望</span><span>月</span></div><div className="wall-sky-title"><span>第四摊 · 月下寄语</span><h1>把心愿，<br/>交给今晚的月亮。</h1><p>千里同月，灯火相望。<br/>愿你心有所念，终得团圆。</p></div><div className="wall-floating" aria-label={demo?'示例祝福':'本机祝福'}>{shown.slice(0,5).map((w,i)=><div key={w.id} className={'wall-float wall-float-'+i}><span className="wall-lantern">福<i/></span><p>{w.text}<small>{w.name}{demo?' · 示例':''}</small></p></div>)}</div><div className="wall-sky-foot"><span>✦ {demo?'当前展示示例祝福，写下第一条属于你的心愿':`已有 ${wishes.length} 盏本机心愿灯被点亮`}</span><span>月满中秋 · 岁岁常安</span></div></section><section className="wall-content"><div className="wall-form-panel"><p className="wall-eyebrow">落笔成愿 · 提灯寄情</p><h2>写一封，给月亮的短信</h2><form onSubmit={submit}><label htmlFor="wall-name">你的昵称 <span>选填</span></label><input id="wall-name" value={name} onChange={e=>setName(e.target.value)} maxLength={12} placeholder="留个名字，或做一位赏月人"/><label htmlFor="wall-message">想说的话</label><div className="wall-textarea-wrap"><textarea id="wall-message" value={message} onChange={e=>{setMessage(e.target.value);setFeedback('')}} maxLength={40} placeholder="今夜月色很美，而我想对你说……" rows={4}/><span>{message.length} / 40</span></div><div className="wall-quick" aria-label="快捷祝福">{quick.map(q=><button key={q} type="button" onClick={()=>{setMessage(q);setFeedback('')}}>{q}</button>)}</div><button className="wall-submit" type="submit">点亮我的心愿灯 <span>↗</span></button><p className="wall-feedback" role="status" aria-live="polite">{feedback||'留言仅保存在当前浏览器，不会公开发送。'}</p></form></div><div className="wall-records"><div className="wall-records-heading"><div><p className="wall-eyebrow">一字一句，都是心意</p><h2>{demo?'月下祝福 · 示例':'我的心愿灯'}</h2></div><span>{demo?'示例展示':`${wishes.length} 条本机留言`}</span></div>{shown.map(w=><article key={w.id} className="wall-record"><div className="wall-record-top"><span className="wall-avatar">{w.name.slice(0,1)}</span><div><strong>{w.name}</strong><small>{demo?'示例祝福 · 非真实访客留言':new Date(w.date).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></div>{!demo&&<button className="wall-delete" onClick={()=>setDeleteId(w.id)} aria-label={`删除${w.name}的留言`}>删除</button>}</div><p>{w.text}</p>{deleteId===w.id&&<div className="wall-delete-confirm"><span>删除这条留言？</span><button onClick={()=>setDeleteId(null)}>保留</button><button onClick={()=>remove(w.id)}>确认删除</button></div>}</article>)}<p className="wall-local-note">☾ 这是一面属于你的本机留言墙。不同设备之间不会同步，清除浏览器数据会移除记录。</p></div></section></main>
}
