#!/usr/bin/env python3
"""Build Unicode-range WOFF2 shards without restricting user-entered text.

Requires: python3 -m pip install 'fonttools[woff]'
Run from any directory: python3 scripts/subset-font.py
The original TTF is retained as the reproducible source, not requested by CSS.
"""

from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'public/fonts/MaShanZheng.ttf'
OUTPUT = ROOT / 'public/fonts/ma-shan-zheng'
CSS = ROOT / 'src/fonts.css'
BLOCK_SIZE = 256


def unicode_points(font):
    return {point for table in font['cmap'].tables if table.isUnicode()
            for point in table.cmap}


def unicode_range(points):
    runs = []
    start = end = points[0]
    for point in points[1:]:
        if point == end + 1:
            end = point
        else:
            runs.append((start, end))
            start = end = point
    runs.append((start, end))
    return ','.join(f'U+{start:X}' if start == end else f'U+{start:X}-{end:X}'
                    for start, end in runs)


def main():
    with TTFont(SOURCE) as original:
        supported = unicode_points(original)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    rules = ['/* Generated by scripts/subset-font.py. All source Unicode glyphs are retained. */']
    coverage = set()
    sizes = []
    expected_files = set()
    for block in sorted({point // BLOCK_SIZE for point in supported}):
        points = sorted(point for point in supported if point // BLOCK_SIZE == block)
        filename = f'{block * BLOCK_SIZE:04x}.woff2'
        destination = OUTPUT / filename
        expected_files.add(destination)
        options = subset.Options()
        options.flavor = 'woff2'
        font = subset.load_font(str(SOURCE), options)
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=points)
        subsetter.subset(font)
        subset.save_font(font, str(destination), options)
        font.close()
        with TTFont(destination) as result:
            actual = unicode_points(result)
        if not set(points).issubset(actual):
            raise RuntimeError(f'Missing glyphs in {filename}: {set(points) - actual}')
        coverage.update(actual)
        sizes.append(destination.stat().st_size)
        rules.append("@font-face{font-family:'Ma Shan Zheng';"
                     f"src:url('/fonts/ma-shan-zheng/{filename}') format('woff2');"
                     "font-weight:400;font-style:normal;font-display:swap;"
                     f"unicode-range:{unicode_range(points)};" + '}')
    if coverage != supported:
        raise RuntimeError(f'Coverage mismatch: {supported ^ coverage}')
    for stale in OUTPUT.glob('*.woff2'):
        if stale not in expected_files:
            stale.unlink()
    CSS.write_text('\n'.join(rules) + '\n', encoding='utf-8')
    print(f'Coverage verified: {len(coverage)} Unicode characters across {len(sizes)} shards.')
    print(f'Total: {sum(sizes):,} bytes; largest shard: {max(sizes):,} bytes; '
          f'original TTF: {SOURCE.stat().st_size:,} bytes.')


if __name__ == '__main__':
    main()
