const flavors=[['白莲蓉','莲','#ead6a4'],['蛋黄莲蓉','黄','#d8a94e'],['经典五仁','仁','#b98359'],['红豆沙','豆','#ae7061'],['抹茶冰皮','茶','#a1b890']];
const cake=(f,i)=>`<span class="arc-cake" style="--cake:${f[2]}">${f[1]}</span>`;
export function mountMooncake(root,ctx){
 let active=false,time=60,score=0,combo=0,best=0,queue=[],timer,processed=0,missed=0,endAt=0,itemDue=0;
 root.innerHTML=`<div class="arc-intro"><div><span class="eyebrow">01 / MOONCAKE WORKSHOP</span><h2>把团圆，分得刚刚好。</h2><p>从传送台最左侧开始，点选对应口味的盘子。连续正确，得分更高。</p></div><button class="btn arc-start">开张营业</button></div><div class="arc-stats"><div><small>剩余时间</small><strong data-time>60 <em>秒</em></strong></div><div><small>本局得分</small><strong data-score>0</strong></div><div><small>连续正确</small><strong data-combo>0</strong></div><div><small>历史最高</small><strong data-record>${ctx.get('moon-best',0)}</strong></div></div><div class="arc-workshop"><div class="arc-belt-title"><span>月饼传送台</span><span>← 请先分拣最左一枚</span></div><div class="arc-belt"></div><div class="arc-conveyor-status"><span data-difficulty>难度 1 · 每枚 4.0 秒</span><span data-missed>漏单 0</span><span data-item-time>等待开张</span></div><div class="arc-deadline"><i></i></div><p class="arc-feedback" role="status">五种口味，五份心意。准备好就开始吧。</p><div class="arc-plates">${flavors.map((f,i)=>`<button class="arc-plate" data-flavor="${i}" aria-label="${f[0]}，快捷键${i+1}">${cake(f,i)}<b>${f[0]}</b><small>按 ${i+1} 键</small></button>`).join('')}</div></div><details class="arc-guide"><summary>打开月饼图鉴 <span>五味团圆 · 玩法说明</span></summary><div class="arc-flavor-guide">${flavors.map((f,i)=>`<div>${cake(f,i)}<h3>${f[0]}</h3><p>${['清甜细腻，莲香悠长。','咸香蛋黄，藏在莲蓉里。','五种果仁，满满传统滋味。','红豆绵密，甜而不腻。','一抹茶绿，清新软糯。'][i]}</p></div>`).join('')}</div><p>正确 +10 分，每连对 5 枚增加 5 分奖励；错分扣 5 分并清空连击。每枚月饼初始需在 4 秒内装盘，每处理 10 枚缩短 0.4 秒，最快 1.6 秒；超时自动漏单、扣 5 分并清空连击。60 秒内获得 100 分，即可收集团圆印章。</p></details>`;
 const $=s=>root.querySelector(s); const random=()=>Math.floor(Math.random()*5);
 const allowance=()=>Math.max(1600,4000-Math.floor(processed/10)*400);
 function timing(now){const remaining=active?Math.max(0,itemDue-now):allowance();$('[data-difficulty]').textContent=`难度 ${Math.min(7,1+Math.floor(processed/10))} · 每枚 ${(allowance()/1000).toFixed(1)} 秒`;$('[data-missed]').textContent=`漏单 ${missed}`;$('[data-item-time]').textContent=active?`本枚 ${(remaining/1000).toFixed(1)} 秒`:'等待开张';$('.arc-deadline i').style.width=`${Math.min(100,remaining/allowance()*100)}%`;}
 function advance(now){processed++;queue.shift();queue.push(random());itemDue=now+allowance();draw();timing(now);}
 function tick(now=performance.now()){if(!active)return;time=Math.max(0,Math.ceil((endAt-now)/1000));$('[data-time]').innerHTML=`${time} <em>秒</em>`;while(itemDue<=Math.min(now,endAt)){const due=itemDue;missed++;score=Math.max(0,score-5);combo=0;$('.arc-feedback').textContent='传送台来不及啦！漏单扣 5 分，继续分拣下一枚。';advance(due);}if(now>=endAt){finish();return;}timing(now);}
 function draw(){ $('.arc-belt').innerHTML=queue.map((v,i)=>`<div class="arc-belt-item ${i===0?'arc-current':''}">${cake(flavors[v],v)}<small>${i===0?'当前分拣':'待分拣'}</small></div>`).join('');$('[data-time]').innerHTML=`${time} <em>秒</em>`;$('[data-score]').textContent=score;$('[data-combo]').textContent=combo;}
 function finish(){active=false;clearInterval(timer);best=Math.max(score,ctx.get('moon-best',0));ctx.set('moon-best',best);$('[data-record]').textContent=best;$('.arc-start').textContent='再开一局';$('[data-item-time]').textContent='营业结束';$('.arc-deadline i').style.width='0%';$('.arc-feedback').textContent=`营业结束！本次获得 ${score} 分。${score>=100?'团圆印章已收集。':'达到 100 分即可收集印章，再试一次吧！'}`;if(score>=100)ctx.award('mooncake');}
 function start(){clearInterval(timer);active=true;time=60;score=combo=processed=missed=0;const now=performance.now();endAt=now+60000;itemDue=now+allowance();queue=Array.from({length:5},random);$('.arc-start').textContent='重新开始';$('.arc-feedback').textContent='开张啦！每枚月饼都有分拣期限，留意下方进度条。';draw();timing(now);timer=setInterval(tick,50);}
 function pick(i){if(!active){ctx.toast('请先点击「开张营业」');return;}const now=performance.now();tick(now);if(!active)return;if(i===queue[0]){combo++;score+=10+Math.floor(combo/5)*5;$('.arc-feedback').textContent=`分对啦！${flavors[i][0]}已装盘 · ${combo} 连击`; }else{score=Math.max(0,score-5);combo=0;$('.arc-feedback').textContent=`这枚是${flavors[queue[0]][0]}，扣 5 分，下次看仔细哦。`;}advance(now);}
 $('.arc-start').onclick=start;root.querySelectorAll('[data-flavor]').forEach(b=>b.onclick=()=>pick(+b.dataset.flavor)); const key=e=>{if(/^[1-5]$/.test(e.key)&&!e.repeat){e.preventDefault();pick(+e.key-1);}};window.addEventListener('keydown',key);queue=Array.from({length:5},random);draw();return()=>{clearInterval(timer);window.removeEventListener('keydown',key);};
}
export function mountParkour(root,ctx){
 root.innerHTML=`<div class="arc-intro"><div><span class="eyebrow">05 / MOONLIT JOURNEY</span><h2>跟着玉兔，奔向月亮。</h2><p>空格 / ↑ / 轻点画面起跳，空中可再跳一次。穿过三段月夜，跑满 3000 米。</p></div><div class="arc-actions"><button class="btn arc-run">启程奔月</button><button class="btn secondary arc-pause" disabled>暂停</button></div></div><div class="arc-stats"><div><small>奔月路程</small><strong data-distance>0 <em>/ 3000 m</em></strong></div><div><small>玉兔体力</small><strong data-life>♥ ♥ ♥</strong></div><div><small>收集月币</small><strong data-coins>0</strong></div><div><small>当前旅程</small><strong data-stage>桂花小径</strong></div></div><div class="arc-canvas-wrap"><canvas class="arc-canvas" aria-label="玉兔跑酷游戏，空格键跳跃" tabindex="0"></canvas><div class="arc-run-message">桂花小径 → 流云天阶 → 广寒月宫<br><small>点击「启程奔月」开始冒险</small></div></div><div class="arc-legend"><span>♡ 三次受伤机会</span><span>◈ 护盾：抵挡一次碰撞</span><span>◎ 磁铁：吸收附近月币</span><span>↗ 冲刺：短暂无敌加速</span></div><p class="arc-run-record">本机最远纪录：<strong data-run-record>${ctx.get('parkour-best',0)}</strong> 米</p><p class="arc-run-status" role="status">月亮在前方等你。每 1000 米进入下一关，速度随旅程提升。</p>`;
 const $=s=>root.querySelector(s),canvas=$('canvas'),g=canvas.getContext('2d');let raf,active=false,paused=false,last=0,t=0,distance=0,coins=0,life=3,objects=[],spawn=0,invincible=0,shield=0,magnet=0,dash=0,ground=280,y=280,vy=0,jumps=0,stage=0;
 const stages=['桂花小径','流云天阶','广寒月宫'];let W=1000;canvas.height=360;function resize(){const next=canvas.parentElement.clientWidth<650?640:1000;if(canvas.width!==next){W=next;canvas.width=W;}}resize();const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(canvas.parentElement);
 function ui(){ $('[data-distance]').innerHTML=`${Math.floor(distance)} <em>/ 3000 m</em>`;$('[data-life]').textContent='♥ '.repeat(life)+'♡ '.repeat(3-life);$('[data-coins]').textContent=coins;$('[data-stage]').textContent=stages[stage];}
 function end(won){active=false;$('.arc-pause').disabled=true;$('.arc-run').textContent='再跑一次';$('.arc-run-message').style.display='block';$('.arc-run-message').innerHTML=won?`已抵达广寒月宫！<br><small>收集 ${coins} 枚月币，奔月印章已点亮</small>`:`稍作歇息，再出发吧。<br><small>跑过 ${Math.floor(distance)} 米 · 收集 ${coins} 枚月币</small>`;if(won)ctx.award('parkour');ctx.set('parkour-best',Math.max(Math.floor(distance),ctx.get('parkour-best',0)));$('[data-run-record]').textContent=ctx.get('parkour-best',0);}
 function jump(){if(!active||paused)return;if(jumps<2){vy=-470;jumps++;}}
 function start(){active=true;paused=false;last=0;t=0;distance=coins=stage=0;life=3;objects=[];spawn=1;invincible=shield=magnet=dash=0;y=ground;vy=jumps=0;$('.arc-run-message').style.display='none';$('.arc-pause').disabled=false;$('.arc-pause').textContent='暂停';$('.arc-run').textContent='重新启程';$('.arc-run-status').textContent='轻点跳跃，连续轻点可双跳。看到月币就去收集吧！';ui();canvas.focus();}
 function circle(x,y,r,c){g.fillStyle=c;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill();}
 function render(dt){g.clearRect(0,0,W,360);g.fillStyle=['#efe7d6','#e5e9de','#e6e1d4'][stage];g.fillRect(0,0,W,360);circle(W*.815,87,51,'#e0bc71');circle(W*.815-20,76,6,'#d7ae62');circle(W*.815+23,108,10,'#d7ae62');g.strokeStyle='#284e4030';g.lineWidth=1;for(let i=0;i<8;i++){let x=((i*170-t*15)%1300+1300)%1300-150;g.beginPath();g.ellipse(x,175+(i%3)*15,110,25,0,Math.PI,0);g.stroke();}g.fillStyle='#d0d3b8';g.beginPath();g.moveTo(0,ground);for(let x=0;x<=W;x+=10)g.lineTo(x,ground-12-Math.sin(x/160+t*.1)*12);g.lineTo(W,360);g.lineTo(0,360);g.fill();g.strokeStyle='#284e40';g.beginPath();g.moveTo(0,ground+5);g.lineTo(W,ground+5);g.stroke();g.fillStyle='#284e4050';for(let i=0;i<30;i++){let x=((i*47-t*100)%1100+1100)%1100;g.fillRect(x,310+(i%3)*12,12,1);}
 for(const o of objects){if(o.type==='rock'){g.fillStyle='#ad8d6e';g.strokeStyle='#79664e';g.beginPath();g.moveTo(o.x-20,ground);g.lineTo(o.x-23,ground-25);g.lineTo(o.x-5,ground-44);g.lineTo(o.x+19,ground-32);g.lineTo(o.x+23,ground);g.closePath();g.fill();g.stroke();}else{circle(o.x,o.y,13,o.type==='coin'?'#d1a84f':'#284e40');g.fillStyle='#fff8e8';g.font='bold 15px sans-serif';g.textAlign='center';g.fillText(({coin:'月',shield:'盾',magnet:'磁',dash:'冲'})[o.type],o.x,o.y+5);}}
 g.save();g.translate(135,y);if(invincible>0&&Math.floor(t*12)%2===0)g.globalAlpha=.45;if(shield>0||dash>0){g.strokeStyle=dash>0?'#ae4935':'#c5a053';g.lineWidth=3;g.beginPath();g.arc(0,-25,39,0,Math.PI*2);g.stroke();}g.fillStyle='#faf5e8';g.strokeStyle='#284e40';g.lineWidth=2;g.beginPath();g.ellipse(-4,-23,22,24,0,0,Math.PI*2);g.fill();g.stroke();g.beginPath();g.ellipse(10,-44,17,17,0,0,Math.PI*2);g.fill();g.stroke();for(let z=0;z<2;z++){g.beginPath();g.ellipse(5+z*14,-68,5,19,z*.2,0,Math.PI*2);g.fill();g.stroke();}circle(17,-48,2,'#284e40');circle(-26,-21,7,'#faf5e8');g.fillStyle='#ae4935';g.fillRect(-1,-34,22,5);g.beginPath();g.moveTo(2,-33);g.lineTo(-17,-27);g.lineTo(-8,-23);g.fill();g.strokeStyle='#284e40';g.beginPath();g.moveTo(-12,-5);g.lineTo(-18+(active?Math.sin(t*18)*6:0),1);g.moveTo(9,-4);g.lineTo(18-(active?Math.sin(t*18)*6:0),1);g.stroke();g.restore();if(shield||magnet>0||dash>0){g.fillStyle='#284e40';g.font='14px sans-serif';g.textAlign='left';g.fillText(`${shield?'护盾已装备  ':''}${magnet>0?'磁铁 '+Math.ceil(magnet)+'s  ':''}${dash>0?'冲刺 '+Math.ceil(dash)+'s':''}`,25,30);}}
 function frame(ts){let dt=Math.min((ts-last)/1000||0,.035);last=ts;if(active&&!paused){t+=dt;const speed=(285+stage*45)*(dash>0?1.55:1);distance=Math.min(3000,distance+dt*speed/7);stage=Math.min(2,Math.floor(distance/1000));invincible=Math.max(0,invincible-dt);magnet=Math.max(0,magnet-dt);dash=Math.max(0,dash-dt);vy+=1150*dt;y+=vy*dt;if(y>=ground){y=ground;vy=0;jumps=0;}spawn-=dt;if(spawn<=0){const r=Math.random();objects.push({x:W+50,type:r<.49?'rock':r<.84?'coin':r<.90?'shield':r<.96?'magnet':'dash',y:ground-55-Math.random()*65});spawn=.95+Math.random()*.65;}for(const o of objects){o.x-=speed*dt;if(o.hit)continue;if(o.type==='rock'){if(Math.abs(o.x-135)<36&&y>ground-44){o.hit=true;if(dash>0||invincible>0){}else if(shield){shield=0;invincible=1;}else{life--;invincible=1.5;$('.arc-run-status').textContent='撞到月石了！提前起跳，空中还能再跳一次。';if(life<=0)end(false);}}}else if(Math.hypot(o.x-135,o.y-(y-28))<(magnet>0&&o.type==='coin'?160:40)){o.hit=true;if(o.type==='coin')coins++;if(o.type==='shield')shield=1;if(o.type==='magnet')magnet=8;if(o.type==='dash')dash=4;}}objects=objects.filter(o=>o.x>-50&&!(o.hit&&o.type!=='rock'));ui();if(distance>=3000&&active)end(true);}render(dt);raf=requestAnimationFrame(frame);}
 $('.arc-run').onclick=start;$('.arc-pause').onclick=()=>{paused=!paused;$('.arc-pause').textContent=paused?'继续':'暂停';$('.arc-run-message').style.display=paused?'block':'none';$('.arc-run-message').innerHTML='月下小憩<br><small>点击「继续」返回旅程</small>';};canvas.addEventListener('pointerdown',jump);const key=e=>{if(e.code==='Space'||e.code==='ArrowUp'){if(e.target instanceof HTMLElement&&['BUTTON','INPUT','SUMMARY'].includes(e.target.tagName))return;e.preventDefault();if(!e.repeat)jump();}};window.addEventListener('keydown',key);raf=requestAnimationFrame(frame);return()=>{resizeObserver.disconnect();cancelAnimationFrame(raf);window.removeEventListener('keydown',key);canvas.removeEventListener('pointerdown',jump);};
}
